export const RETIE_ACP_SDE_BCI_SCHEMA = {
  hoja: 'ACP-SDE-BCI',
  titulo: 'LISTA DE CHEQUEO ALTA CONCENTRACIÓN DE PERSONAS, SISTEMAS DE EMERGENCIA Y BOMBAS CONTRA INCENDIOS',
  proceso: 'GESTION DE INSPECCION',
  codigo: 'F-GI-07',
  version: '1',
  fecha_formato: '19/01/2018',
  instruccion_excel: 'Colocar X o ü según la evaluación a cada uno de los ítems',
  imagenes_embebidas: [
    { id: 'acp_sde_bci_imagen_1', file: 'ACP_SDE_BCI_IMAGEN_1.png', rol: 'encabezado_pagina', descripcion: 'Imagen de encabezado de página de la hoja ACP-SDE-BCI.' },
    { id: 'acp_sde_bci_imagen_2', file: 'ACP_SDE_BCI_IMAGEN_2.png', rol: 'encabezado_pagina', descripcion: 'Imagen de encabezado de página de la hoja ACP-SDE-BCI.' },
    { id: 'acp_sde_bci_imagen_3', file: 'ACP_SDE_BCI_IMAGEN_3.png', rol: 'encabezado_pagina', descripcion: 'Imagen de encabezado de página de la hoja ACP-SDE-BCI.' },
  ],
  campos_contexto: [
    { id: 'codigo_servicio', label: 'Código servicio:', tipo: 'text', valor_excel: 'R&F-0467-10-20' },
    { id: 'fecha_inspeccion', label: 'Fecha de la inspección:', tipo: 'date', valor_excel: '2020-10-29 00:00:00' },
    { id: 'fecha_cierre_no_conformidades', label: 'Fecha de cierre no conformidades:', tipo: 'text', valor_excel: 'N/A' },
  ],
  secciones: [
    {
      id: '1__Tableros',
      titulo: '1. Tableros',
      preguntas: [
        { id: 'ACP-SDE-BCI-001', numero: 1, norma: 'R.27.4.3.d', pregunta: 'El Tablero de Distribucion es fácilmente accesible', valor_excel: '' },
        { id: 'ACP-SDE-BCI-002', numero: 2, norma: 'R. 10.4. N. 110-16', pregunta: 'Se cumple con las distancias mínimas permitidas para el espacio de trabajo. Las puertas abren minimo 90°.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-003', numero: 3, norma: 'R. 20.23.1.4.f', pregunta: 'El tablero tiene logo de riesgo eléctrico e identificación.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-004', numero: 4, norma: 'N. 110-16.f.1', pregunta: 'En paneles de distribucion y centros de control de motores ubicados en interiores se cumple espacio dedicado,en esta zona no se debe ubicar tuberia, ductos o equipos ajenos, se permiten rociadores. Para la instalacion se dispone de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta una altura de 7.6 m o hasta el techo,', valor_excel: '' },
        { id: 'ACP-SDE-BCI-005', numero: 5, norma: 'R. 20.23.1.4.a-e', pregunta: 'El tablero tiene adherida de manera clara, permanente y visible placa con características técnicas.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-006', numero: 6, norma: 'R. 20.23.1.4.g,i', pregunta: 'El tablero tiene cuadro para identificar circuitos y diagrama unifilar actualizado.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-007', numero: 7, norma: 'R. 20.5.2. f', pregunta: 'Las aberturas no utilizadas están cerradas eficazmente', valor_excel: '' },
        { id: 'ACP-SDE-BCI-008', numero: 8, norma: 'N. 373-8', pregunta: 'NO existen empalmes dentro del tablero.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-009', numero: 9, norma: 'R.20.23.4.g', pregunta: 'Los cables no atraviesan barrajes', valor_excel: '' },
        { id: 'ACP-SDE-BCI-010', numero: 10, norma: 'R. 20.23.1.3.f', pregunta: 'Se cumple el código de colores.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-011', numero: 11, norma: 'R.6.3', pregunta: 'Ningún circuito utiliza el blanco ni el verde para las fases.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-012', numero: 12, norma: 'R.20.2.9.j', pregunta: 'Cables o alambres de Aluminio o Alumino recubierto en cobre se cumple lo siguiente: 1. Son de la serie AA 8000.-2. Empleo de conectores bimetálicos - 3. Ser instalados y mantenidos por personas calificadas, con la competencia profesional certificada. -4. A toda conexión se le aplica gel retardantes de la oxidación. -5. Sobre el cuerpo del dispositivo o equipo para uso directo con conductores de aluminio, se fija rotulado de advertencia en fondo de color amarillo y letra negra.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-013', numero: 13, norma: 'R. 27.4.3. c.', pregunta: 'La capacidad de corriente del conductor de cada circuito ramal es superior a la capacidad de corriente de la protección asociada. Ver tabla 310-16 NTC 2050.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-014', numero: 14, norma: 'N. 250-95', pregunta: 'Cuando haya conductores en paralelo (sólo para mayores a calibres 1/0 AWG de Cu o Al) en varios conductos o cables, como lo permite el Artículo 310-4, el conductor de puesta a tierra de equipos, cuando exista está instalado en paralelo.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-015', numero: 15, norma: 'R.20.16.2.2.e', pregunta: 'Cada circuito ramal presenta protección contra sobrecorriente.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-016', numero: 16, norma: 'R.27.4.1.e', pregunta: 'Cada circuito dispone de dispositivo de corte automático de la alimentación.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-017', numero: 17, norma: 'R.20.16.2.2.a', pregunta: 'En los interruptores automáticos el circuito alimentador llegue al terminal línea y la salida se conecte a los terminales carga.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-018', numero: 18, norma: 'R.20.16.2.2.b', pregunta: 'Los interruptores automáticos tienen unas especificaciones de corriente y tensión, no menores a los valores nominales de los circuitos que controlan.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-019', numero: 19, norma: 'R. 20.23.1.3. c.', pregunta: 'El tablero cuenta con barrajes de tierra y neutro, con suficientes terminales de salida.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-020', numero: 20, norma: 'R.20.12.2.a', pregunta: 'No se instala dos o más conectores o terminales en la misma bornera o al mismo tornillo.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-021', numero: 21, norma: 'R.20.23.1.2.e', pregunta: 'El tablero se encuentra sólidamente puesto a tierra.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-022', numero: 22, norma: 'R. 15.3.3.d.', pregunta: 'El conductor de puesta a tierra de equipos acompaña los conductores activos durante todo su recorrido y por la misma canalización.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-023', numero: 23, norma: 'R.15.3.3.c', pregunta: 'El Conductor de puesta a tierra de equipos es continuo, sin interruptores o medios de desconexión y cuando se empalmen (es mecánica y eléctricamente seguro con soldadura o conector certificados para tal uso)', valor_excel: '' },
        { id: 'ACP-SDE-BCI-024', numero: 24, norma: 'R.15.3.3.e', pregunta: 'El Conductor de puesta a tierra de equipos que por disposición de la instalación se requieran aislar, son de color verde, verde con rayas amarillas o identificados con marcas verdes en los puntos de inspección y extremos', valor_excel: '' },
        { id: 'ACP-SDE-BCI-025', numero: 25, norma: 'N. 250-95', pregunta: 'El conductor de tierra de cada circuito ramal cumple el calibre mínimo dado en la tabla 250-95 NTC 2050.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-026', numero: 26, norma: 'N.280-21', pregunta: 'Circuito de menos de 1000 V los conductores de conexión DPS a la red y a tierra no son de calibre menor a 14 AWG en Cu o 12 AWG en Al.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-027', numero: 27, norma: 'N.280-4.a', pregunta: 'Circuito de menos de 1000 V el valor nominal del descargador de sobretensiones es = o mayor que la máxima tensión continua de fase a tierra', valor_excel: '' },
        { id: 'ACP-SDE-BCI-028', numero: 28, norma: 'R.20.23.4.o', pregunta: 'Realizar las pruebas de aislamiento: Las mediciones se realizan usando un megómetro a una tensión de por lo menos 500 Vcc. El valor de la resistencia de aislamiento no es menor de 1000 Ω/V.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-029', numero: 29, norma: 'R.20.23.4.o', pregunta: 'Se deben realizar las siguientes verificaciones: 1. Funcionalidad de las rejillas de ventilación, las tapas laterales y las puertas. 2. Identificaciones del tablero y de los conductores de control y potencia. 3. Conexión a tierra de las puertas. 4. Remover el polvo. 5. Medir equipotencialidad entre partes conductoras del tablero. 6. Verificar los torques de las uniones mecánicas, eléctricas y de anclaje. 7. Verificar  los enclavamientos mecánicos de los equipos del tablero. 8. Inspeccionar visualmente de toda la estructura del tablero, especialmente la pintura. 9.Remover todos los objetos extraños (restos de cables, tuercas, tornillos, herramientas, etc)', valor_excel: '' },
      ],
    },
    {
      id: '2__Alta_Concentraci_n_de_Personas',
      titulo: '2. Alta Concentración de Personas',
      preguntas: [
        { id: 'ACP-SDE-BCI-030', numero: 30, norma: 'R. 28.3.3', pregunta: 'La instalacion eléctrica pertenece a aquellos lugares que en cualquier momento se puedan reunir simultáneamente más de 50 personas, tales como son sitios de reuniones públicas, grandes supermercados, lugares de espectáculos como teatros, áreas de audiencias de cine o televisión, carnavales, circos, ferias y espectáculos similares, auditorios, boleras, comedores públicos, cuarteles, gimnasios, iglesias, museos, pistas de patinaje, restaurantes o centros de comidas, salas de conferencias; salas de espera de aeropuertos, puertos y estaciones de transporte masivo; salas de exhibición, salas de juegos, salas de reuniones, salas de uso múltiples, salas de velación, salones de baile', valor_excel: '' },
        { id: 'ACP-SDE-BCI-031', numero: 31, norma: 'R. 28.3.3 a.', pregunta: 'En lugares con alta concentración de personas la instalación dispone de un sistema de potencia de emergencia, destinados a suministrar automáticamente energía eléctrica dentro de los 10 segundos siguientes al corte, a los sistemas de alumbrado y fuerza para áreas y equipos previamente definidos', valor_excel: '' },
        { id: 'ACP-SDE-BCI-032', numero: 32, norma: 'R. 28.3.3 b.', pregunta: 'Los sistemas de emergencia  suministran energía a: las señales de salida, la ventilación, alarma contra incendio, bombas contra incendio, ascensores, sistemas de comunicación, procesos industriales y demás sistemas en los que la interrupción del suministro eléctrico puede producir serios peligros para la seguridad de la vida humana.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-033', numero: 33, norma: 'R. 28.3.3 b.', pregunta: 'El sistema de emergencia provee autonomía por lo menos 60 minutos a plena carga, sin que la tensión baje del 87,5 % de su valor nominal.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-034', numero: 34, norma: 'R. 28.3.3 b.', pregunta: 'Cuando el sistema de emergencia utilice grupos de baterías de acumuladores, estos cuentan con cargador automático.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-035', numero: 35, norma: 'R. 28.3.3 c.', pregunta: 'Las subestaciones para el servicio de lugares con alta concentración de personas o donde el fuego producido por el aceite de transformadores se pueda propagar en todo el edificio, no tiene transformadores con aislamiento en aceite a menos que estén confinados en una bóveda con resistencia al fuego mínimo de tres horas.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-036', numero: 36, norma: 'R. 20.2.9 g.', pregunta: 'En lugares con alta concentración de personas se utiliza conductores eléctricos con aislamiento o recubrimiento de muy bajo contenido de halógenos, no mayor a 0,5%, no propagadores de llama y baja emisión de humos opacos.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-037', numero: 37, norma: 'R. 20.2.9 g.', pregunta: 'Los conductores de los cables de bajo contenido de halógenos, son del tipo cableado, no se admiten conductores sólidos.', valor_excel: '' },
      ],
    },
    {
      id: '3__Iluminaci_n_de_Emergencia',
      titulo: '3. Iluminación de Emergencia',
      preguntas: [
        { id: 'ACP-SDE-BCI-038', numero: 38, norma: 'RETILAP. 470.2', pregunta: 'La instalación pertenece a alguno de los siguientes lugares: a) Los edificios de más de 5 pisos o edificios que en cualquier hora de la noche concentren más de 100 personas; b) Todo recinto cuya ocupación sea mayor a 100 personas; c) Recorridos de las rutas de evacuación; d) Parqueaderos cerrados o cubiertos cuya superficie construida exceda de 100 m²; e) Zonas de baños en edificios de uso público; f) Lugares en los que se ubican tableros de distribución o de accionamiento de la instalación de alumbrado; g) Instalaciones que por reglamentaciones especiales requiera de alumbrado de emergencia.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-039', numero: 39, norma: 'R. 17.1 a.', pregunta: 'La instalación eléctrica y los equipos asociados garantizan el suministro ininterrumpido para iluminación en sitios, tal como en áreas críticas, salidas de emergencia o rutas de evacuación.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-040', numero: 40, norma: 'R. 17.1 e.', pregunta: 'Las rutas de evacuación están claramente visibles, señalizadas e iluminadas con un sistema autónomo con batería.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-041', numero: 41, norma: 'R. 17.1 c.', pregunta: 'El sistema de alumbrado de emergencia equipados con grupos de baterías garantiza su funcionamiento por lo menos durante 60 minutos.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-042', numero: 42, norma: 'R. 17.1.b', pregunta: 'En circuitos de iluminación de emergencia no se utiliza lámparas de descarga con encendido retardado.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-043', numero: 43, norma: 'R. 17.1.f.', pregunta: 'Las luminarias tienen una hermeticidad no menor a IP20 para uso en interiores e IP65 para uso exterior.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-044', numero: 44, norma: 'R. 17.1.d', pregunta: 'En los lugares en los que estén situados los equipos de emergencia como extintores y camillas, en las instalaciones de protección contra incendios de utilización manual y en los tableros de distribución del alumbrado, la iluminancia horizontal es mínimo de 5 lux a la altura del plano de uso.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-045', numero: 45, norma: 'N. 700-15.', pregunta: 'A los circuitos de alumbrado de emergencia no se conectan otros artefactos ni bombillas que no sean los específicos del sistema de emergencia.', valor_excel: '' },
      ],
    },
    {
      id: '4__Sistemas_de_Emergencia',
      titulo: '4. Sistemas de Emergencia',
      preguntas: [
        { id: 'ACP-SDE-BCI-046', numero: 46, norma: 'N. 700-7.', pregunta: 'El sistema de emergencia cuenta con dispositivos de señalización sonora y visual para: a) Avería; b) Carga (batería); c) No funcionalidad (cargador de batería); d) Falla a tierra.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-047', numero: 47, norma: 'N. 700-6.', pregunta: 'El equipo de transferencia es automático', valor_excel: '' },
        { id: 'ACP-SDE-BCI-048', numero: 48, norma: 'N. 700-8.a', pregunta: 'En el equipo de entrada de la acometida existe un diagrama (plano, diagrama unifilar) que indique el tipo y la ubicación de las fuentes internas (plantas, ups, etc.) para suministro de emergencia.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-049', numero: 49, norma: 'N. 700-9.a', pregunta: 'Todas las cajas y encerramientos (tableros, transferencias) de los circuitos de emergencia tienen rótulos permanentes que permiten identificarlas fácilmente como pertenecientes a un sistema o circuito de emergencia.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-050', numero: 50, norma: 'N. 700-9.b', pregunta: 'El alambrado desde la fuente de emergencia (planta, grupo electrógeno, etc.) o desde la protección contra sobrecorriente de la fuente de distribución de emergencia hasta las cargas del sistema de emergencia, es totalmente independiente de cualquier otro alambrado y equipos y no esta en la misma canalización, cable, caja o gabinete con otro alambrado.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-051', numero: 51, norma: 'N. 700-9.b', pregunta: 'Los circuitos del alambrado de emergencia están ubicados minimizando los riesgos de fallos por inundaciones, incendios, congelamiento, vandalismo y otras condiciones adversas', valor_excel: '' },
        { id: 'ACP-SDE-BCI-052', numero: 52, norma: 'N. 700-12.a', pregunta: 'La instalación cuenta con un medio de carga automática de las baterías.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-053', numero: 53, norma: 'N. 700-12.d', pregunta: 'Cuando lo acepte la autoridad competente como adecuado para un sistema de emergencia, se permite instalar una segunda acometida.', valor_excel: '' },
      ],
    },
    {
      id: '5__Planta_de_emergencia',
      titulo: '5. Planta de emergencia',
      preguntas: [
        { id: 'ACP-SDE-BCI-054', numero: 54, norma: 'R. 24.2. g.', pregunta: 'La planta de emergencia se encuentra separada de los equipos eléctricos de la subestación o de cuartos eléctricos, por un muro o barrera.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-055', numero: 55, norma: 'R. 10.4', pregunta: 'En el cuarto donde se ubica la planta de emergencia, el ancho del ala de las puertas de acceso al espacio de trabajo no es menor a 90 cm', valor_excel: '' },
        { id: 'ACP-SDE-BCI-056', numero: 56, norma: 'R. 10.4', pregunta: 'La planta se encuentra instalada de tal modo que se respetan las distancias mínimas para el espacio de trabajo.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-057', numero: 57, norma: 'N. 700-12.b.2', pregunta: 'La planta cuenta con un depósito y un sistema de alimentación de combustible suficiente para que pueda funcionar durante dos horas como mínimo.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-058', numero: 58, norma: 'N. 695-3.a.2', pregunta: 'El generador que suple la BCI está instalado y protegido de modo que se reduzca al mínimo la posibilidad de daños por los incendios', valor_excel: '' },
        { id: 'ACP-SDE-BCI-059', numero: 59, norma: 'N. 110-17.c', pregunta: 'En la puerta de acceso a la planta de emergencia se encuentran ubicadas señales de seguridad.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-060', numero: 60, norma: 'N. 110-16.d', pregunta: 'El cuarto de la planta de emergencia cuenta con iluminación suficiente.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-061', numero: 61, norma: 'R. 28.3.3.b', pregunta: 'Cuando se use grupo electrógeno, en el cuarto se dispone de tomacorrientes para el precalentado, el cargador de baterías y para cualquier otro uso necesario.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-062', numero: 62, norma: 'R. 15', pregunta: 'Los apoyos o estructuras metálicas ubicados en el cuarto se encuentran puestos a tierra.', valor_excel: '' },
      ],
    },
    {
      id: '6__Bombas_Contra_Incendios',
      titulo: '6. Bombas Contra Incendios',
      preguntas: [
        { id: 'ACP-SDE-BCI-063', numero: 63, norma: 'R. 28.3.11 a.', pregunta: 'La bomba contraincendios es alimentada desde una acometida independiente o desde un grupo electrógeno de emergencia.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-064', numero: 64, norma: 'R. 28.3.11 a.', pregunta: 'En el cableado de alimentación de la bomba contraincendios se instalan barreras cortafuego.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-065', numero: 65, norma: 'R. 28.3.11 b.', pregunta: 'El controlador de la bomba esta certificado para bombas contra incendios.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-066', numero: 66, norma: 'R. 28.3.11 b.', pregunta: 'La bomba cuenta con un elemento de protección solo contra corto circuito no contra sobrecarga.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-067', numero: 67, norma: 'R. 28.3.11 c.', pregunta: 'La fuente que alimenta la bomba es confiable y tiene la capacidad para soportar las corrientes de rotor bloqueado de la motobomba y de los equipos accesorios.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-068', numero: 68, norma: 'R. 28.3.11 d.', pregunta: 'La medida del consumo de energía del sistema contra incendios se hace con equipo de medición indirecto.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-069', numero: 69, norma: 'N. 695-3. a) 1)', pregunta: 'El motor está ubicado e instalado de modo que se reduzca al mínimo la posibilidad de daño por los incendios producidos en el interior del predio y exposición a otros riesgos.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-070', numero: 70, norma: 'N. 695.3. b); N.230-2.a  Excepción 1; N. 230-72. b)', pregunta: 'Si el motor de la BCI recibe la corriente desde una acometida independiente o desde una derivación adelante de un medio de desconexión de acometida: -Se permite otra acometida siempre y cuando se requiera una acometida independiente para bombas contra incendios; -El medio o medios adicionales de desconexión de la acometida para bombas contra incendios, emergencia, servicios de reserva legalmente exigidos o servicios de reserva opcionales permitidos por el Artículo 230-2, se instalaron a distancia suficiente de los uno a seis medios de desconexión normales de la acometida, de manera que se reduzca al mínimo la posibilidad de corte simultáneo de la alimentación.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-071', numero: 71, norma: 'N. 695-3. c)', pregunta: 'Cuando el motor de la BCI reciba corriente desde una derivación adelante del medio de desconexión de la acometida, dicha derivación no esta hecha dentro del compartimiento del medio de desconexión de acometida', valor_excel: '' },
        { id: 'ACP-SDE-BCI-072', numero: 72, norma: 'N. 695-3. d)', pregunta: 'Los conductores de suministro conectan directamente la fuente de alimentación con un controlador certificado para bombas contra incendios.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-073', numero: 73, norma: 'N. 695.4. a)', pregunta: 'Fuentes de alimentación múltiples. Cuando no sea posible disponer de suministro eléctrico confiable desde una fuente según lo que establece el Artículo 695-3.a (ACOMETIDA O GENERADOR), se debe conseguir mediante la combinación de dos o más de los medios anteriormente descritos o con uno o más de esos medios en combinación con generador interno, todos ellos aprobados por la autoridad competente. Las fuentes de alimentación se deben conectar de modo que un incendio en una de ellas no impida que funcionen las demás.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-074', numero: 74, norma: 'N. 695.4.b', pregunta: 'Conexión directa. Los conductores de suministro deben conectar directamente las fuentes de alimentación a una combinación certificada de controlador de bombas y conmutador de transferencia o a un medio de desconexión y dispositivo(s) de protección contra sobrecorriente que cumplan los requisitos del Artículo 695-3.C (acometida, dicha derivación no debe estar hecha dentro del compartimiento del medio de desconexión de acometida)', valor_excel: '' },
        { id: 'ACP-SDE-BCI-075', numero: 75, norma: 'N. 695.5. a', pregunta: 'Dimensionamiento. Cuando un transformador se dedique para dar suministro a una instalación de bombas contra incendios, su corriente nominal es como mínimo el 125 % de la suma de: 1) La corriente a plena carga de todos los motores de las bombas. 2) La corriente a plena carga de todos los motores de las bombas de mantenimiento de presión que estén conectados al mismo circuito de suministro. 3) La corriente a plena carga de todos los equipos accesorios relacionados con las bombas cuando estén conectados al mismo circuito de suministro.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-076', numero: 76, norma: 'N. 695.5.b.1', pregunta: 'No se permite instalar protección contra sobrecorriente en el secundario (en transformadores para BCI)', valor_excel: '' },
        { id: 'ACP-SDE-BCI-077', numero: 77, norma: 'N. 695-7.a', pregunta: 'Los controladores de los motores eléctricos de las bombas y los conmutadores de transferencia están ubicados lo más cerca posible de los motores que controlan y a la vista de ellos.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-078', numero: 78, norma: 'N. 695-7.e', pregunta: 'El controladores para motores de las bombas y conmutadores de transferencia están ubicados o protegidos para que no les llegue el agua procedente de las bombas o sus conexiones (tubería).', valor_excel: '' },
        { id: 'ACP-SDE-BCI-079', numero: 79, norma: 'N. 695-7.d', pregunta: 'Todas las partes de equipos que puedan estar energizadas se encuentran ubicadas a 0,305m como mínimo sobre el nivel del piso.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-080', numero: 80, norma: 'N. 695-7.f', pregunta: 'Todos los equipos de control de las bombas contra incendios están bien sujetos a estructuras de soporte de material no combustible.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-081', numero: 81, norma: 'N. 695-8.a', pregunta: 'Los conductores de suministro van por la parte exterior de las edificaciones y están instalados como conductores de entrada de acometida. Cuando físicamente no puedan instalarse por fuera de la edificación, se permite instalarlos por dentro siempre que estén enterrados o encerrados bajo hormigón de un espesor mínimo de 50 mm.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-082', numero: 82, norma: 'N. 695-8.b', pregunta: 'El alambrado desde los controladores de los motores de las bombas hasta dichos motores están instalados en tubo de metal rígido, tubo metálico intermedio, tubo metálico flexible hermético a los líquidos o cable de Tipo MI.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-083', numero: 83, norma: 'N. 695-8.d', pregunta: 'Los controladores de las bombas contra incendios no son usados como cajas de unión para dar suministro a otros equipos.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-084', numero: 84, norma: 'N. 695-8.d', pregunta: 'No están conectados a los controladores de las bombas contra incendios, los conductores de suministro de las bombas para mantenimiento de la presión.', valor_excel: '' },
        { id: 'ACP-SDE-BCI-085', numero: 85, norma: 'R. 15', pregunta: 'Los apoyos o estructuras metálicas se encuentran puestas a tierra.', valor_excel: '' },
      ],
    },
  ],
  observaciones: { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
};

export default RETIE_ACP_SDE_BCI_SCHEMA;