export const RETIE_CARPETA_SCHEMA = {
  hoja: 'CARPETA',
  titulo: 'LISTA DE CHEQUEO DOCUMENTOS CARPETA',
  proceso: 'GESTIÓN DE INSPECCIÓN',
  codigo: 'F-GI-02',
  version: '3',
  fecha_formato: '15/01/2018',
  instruccion_excel: 'Coloque X o  ü según la evaluación a cada uno de los ítems',
  subinstruccion_excel: 'Organizar los documentos en la carpeta de inspección siguiendo el orden dado a continuación',
  campos_contexto: [
    { id: 'codigo_servicio', label: 'Código del servicio:', tipo: 'text' },
    { id: 'fecha_inspeccion', label: 'Fecha de la inspección:', tipo: 'date' },
  ],
  items: [
    { id: 'CARP-001', numero: 1, descripcion: 'Asignación orden de trabajo', archivo_digital: true },
    { id: 'CARP-002', numero: 2, descripcion: 'Evaluación del riesgo', archivo_digital: true },
    { id: 'CARP-003', numero: 3, descripcion: 'Declaración de cumplimiento del constructor', archivo_digital: true },
    { id: 'CARP-004', numero: 4, descripcion: 'Acta de visita', archivo_digital: true },
    { id: 'CARP-005', numero: 5, descripcion: 'Copia matricula profesional del constructor eléctrico', archivo_digital: true },
    { id: 'CARP-006', numero: 6, descripcion: 'Copia matricula profesional del diseñador eléctrico', archivo_digital: true },
    { id: 'CARP-007', numero: 7, descripcion: 'Copia matricula profesional del interventor de la obra eléctrica', archivo_digital: true },
    { id: 'CARP-008', numero: 8, descripcion: 'Copia cedula de ciudadanía o NIT del propietario', archivo_digital: true },
    { id: 'CARP-009', numero: 9, descripcion: 'Lista de chequeo revisión documental de diseños', archivo_digital: true },
    { id: 'CARP-010', numero: 10, descripcion: 'Planos eléctricos según lo construido firmado por el diseñador y constructor', archivo_digital: true },
    { id: 'CARP-011', numero: 11, descripcion: 'Memorias de cálculo firmadas por diseñador', archivo_digital: true },
    { id: 'CARP-012', numero: 12, descripcion: 'Lista de chequeo uso final residencial', archivo_digital: true },
    { id: 'CARP-013', numero: 13, descripcion: 'Lista de chequeo uso final industrial y comercial', archivo_digital: true },
    { id: 'CARP-014', numero: 14, descripcion: 'Lista de chequeo alta concentración de personas, sistemas de emergencia y bombas contra incendios', archivo_digital: true },
    { id: 'CARP-015', numero: 15, descripcion: 'Lista de chequeo apantallamiento', archivo_digital: true },
    { id: 'CARP-016', numero: 16, descripcion: 'Lista de chequeo ascensores', archivo_digital: true },
    { id: 'CARP-017', numero: 17, descripcion: 'Lista de chequeo piscinas', archivo_digital: true },
    { id: 'CARP-018', numero: 18, descripcion: 'Lista de chequeo distribución', archivo_digital: true },
    { id: 'CARP-019', numero: 19, descripcion: 'Lista de chequeo subestación tipo poste', archivo_digital: true },
    { id: 'CARP-020', numero: 20, descripcion: 'Lista de chequeo subestación tipo pedestal', archivo_digital: true },
    { id: 'CARP-021', numero: 21, descripcion: 'Lista de chequeo subestación tipo interior', archivo_digital: true },
    { id: 'CARP-022', numero: 22, descripcion: 'Lista de chequeo subestación tipo patio', archivo_digital: true },
    { id: 'CARP-023', numero: 23, descripcion: 'Lista de chequeo certificado de producto', archivo_digital: true },
    { id: 'CARP-024', numero: 24, descripcion: 'Medida resistencia de puesta a tierra', archivo_digital: true },
    { id: 'CARP-025', numero: 25, descripcion: 'Medida resistencia de aislamiento', archivo_digital: true },
    { id: 'CARP-026', numero: 26, descripcion: 'Medida Iluminancia', archivo_digital: true },
    { id: 'CARP-027', numero: 27, descripcion: 'Medida tensión de paso y contacto', archivo_digital: true },
    { id: 'CARP-028', numero: 28, descripcion: 'Medida de campos electromagnéticos', archivo_digital: true },
    { id: 'CARP-029', numero: 29, descripcion: 'Certificados de productos', archivo_digital: true },
    { id: 'CARP-030', numero: 30, descripcion: 'Protocolo del transformador', archivo_digital: true },
    { id: 'CARP-031', numero: 31, descripcion: 'Registro fotográfico', archivo_digital: true },
    { id: 'CARP-032', numero: 32, descripcion: 'Reporte de no conformidades adicionales', archivo_digital: true },
    { id: 'CARP-033', numero: 33, descripcion: 'Registro inscripción SIC del constructor', archivo_digital: true },
    { id: 'CARP-034', numero: 34, descripcion: 'Dictamen prerrequisito', archivo_digital: true },
  ],
  otros_documentos: [
    { id: 'CARP-OTRO-1', ordinal: '1.', descripcion: 'Declaración de cumplimiento de Diseño' },
    { id: 'CARP-OTRO-2', ordinal: '2.', descripcion: 'Copia Disponibilidad de Servicio' },
    { id: 'CARP-OTRO-3', ordinal: '3.', descripcion: 'Copia declaracion de diseño' },
    { id: 'CARP-OTRO-4', ordinal: '4.', descripcion: '' },
    { id: 'CARP-OTRO-5', ordinal: '5.', descripcion: '' },
  ],
};

export default RETIE_CARPETA_SCHEMA;