export const RETIE_DISENO_SCHEMA = {
  hoja: 'DISEÑO',
  titulo: 'LISTA DE CHEQUEO REVISIÓN DOCUMENTAL DE DISEÑOS',
  proceso: 'GESTIÓN DE INSPECCIÓN',
  codigo: 'F-GI-04',
  version: '2',
  fecha_formato: '16/07/2018',
  instruccion_excel: 'Colocar X o ü según la evaluación a cada uno de los ítems',
  campos_contexto: [
    { id: 'codigo_servicio', label: 'Código servicio:', tipo: 'text', valor_excel: 'R&F-0467-10-20' },
    { id: 'fecha_inspeccion', label: 'Fecha de la inspección:', tipo: 'date', valor_excel: '2020-10-29' },
    { id: 'fecha_cierre_no_conformidades', label: 'Fecha de cierre no conformidades:', tipo: 'text', valor_excel: 'N/A' },
  ],
  recursos_visuales_hoja: [
    { id: 'diseno_imagen_1', file: 'DISENO_IMAGEN_1.png', rol: 'encabezado_pagina', descripcion: 'Imagen de encabezado de página de la hoja DISEÑO.' },
  ],
  respuesta_por_defecto: {
    visita_1: { tipo: 'radio', opciones: ['SI', 'NO', 'N/A'] },
    cierre: { tipo: 'radio', opciones: ['SI', 'NO'] },
  },
  secciones: [
    {
      id: 'REQ_GENERALES',
      titulo: '1. Requisitos generales',
      preguntas: [
        { id: 'DISENO-001', numero: 1, norma: 'R.34.2', pregunta: 'Declaración de cumplimiento', valor_excel: 'SI' },
        { id: 'DISENO-002', numero: 2, norma: 'R.34.3', pregunta: 'Copia de Matriculas profesionales de Constructor y Diseñador eléctrico', valor_excel: 'SI' },
        { id: 'DISENO-003', numero: 3, norma: 'R.10.2.2', pregunta: 'Constructor está inscrito en el Registro de Productores e Importadores de Productos (bienes o servicios) de la SIC', valor_excel: 'SI' },
        { id: 'DISENO-004', numero: 4, norma: 'R.10.2.2.b.', pregunta: 'Certificados de Conformidad de Producto', valor_excel: 'SI' },
        { id: 'DISENO-005', numero: 5, norma: 'R.10.2.2.e.', pregunta: 'Se presentan planos finales conforme a la instalación construida y firmados por el constructor', valor_excel: 'SI' },
        { id: 'DISENO-006', numero: 6, norma: 'R.34.10.f', pregunta: 'Copia de dictámenes, relación de dictámenes o constancia firmada del constructor donde se evidencia que los procesos de distribución y transformación se encuentran dictaminados o en curso de inspección (los cuales serán relacionados en el dictamen de servicios comunes)', valor_excel: 'N/A' },
        { id: 'DISENO-007', numero: 7, norma: 'R.3', pregunta: 'Para Alta Concentración de Personas, el diseño evaluó las densidades de personas(NFPA 101).', valor_excel: 'N/A' },
        { id: 'DISENO-008', numero: 8, norma: 'R.17', pregunta: 'Si la edificación requiere diseño RETILAP, el diseño de iluminación fue presentado (incluido el del sistema de emergencia) (firmado por diseñador)', valor_excel: 'N/A' },
        { id: 'DISENO-009', numero: 9, norma: 'R.27.3.c', pregunta: 'La caída de tensión para acometida no supera el 3% de caída de tensión por regulación', valor_excel: 'SI' },
        { id: 'DISENO-010', numero: 10, norma: 'R.20.14.2.e', pregunta: 'El diseño justificó la instalación en la transición de la red MT el DPS, sino se encuentra en el transformador.', valor_excel: 'N/A' },
        { id: 'DISENO-011', numero: 11, norma: 'R.14.4', pregunta: 'Si la edificación se encuentra aledaña a la zona de servidumbre de una línea de transmisión, el diseño incluye cálculo de campo electromagnético para cada piso', valor_excel: 'N/A' },
        { id: 'DISENO-012', numero: 12, norma: 'R.20.25', pregunta: 'Copia Protocolo de pruebas de transformador rebobinado', valor_excel: 'N/A' },
      ],
    },
    {
      id: 'DISENO_DETALLADO',
      titulo: '2. Diseño Detallado',
      preguntas: [
        { id: 'DISENO-013', numero: 13, norma: 'R.10.1.1.a', pregunta: 'Análisis y cuadros de cargas iniciales y futuras, incluyendo análisis de factor de potencia y armónicos.', valor_excel: 'SI' },
        { id: 'DISENO-014', numero: 14, norma: 'R.10.1.1.b', pregunta: 'Análisis de coordinación de aislamiento eléctrico.', valor_excel: 'SI' },
        { id: 'DISENO-015', numero: 15, norma: 'R.10.1.1.c', pregunta: 'Análisis de cortocircuito y falla a tierra.', valor_excel: 'SI' },
        { id: 'DISENO-016', numero: 16, norma: 'R.10.1.1.d', pregunta: 'Análisis de nivel de riesgo por rayos y medidas de protección contra rayos.', valor_excel: 'SI' },
        { id: 'DISENO-017', numero: 17, norma: 'R.10.1.1.e', pregunta: 'Análisis de riesgos de origen eléctrico y medidas para mitigarlos', valor_excel: 'SI' },
        { id: 'DISENO-018', numero: 18, norma: 'R.10.1.1.f', pregunta: 'Análisis del nivel tensión requerido.', valor_excel: 'SI' },
        { id: 'DISENO-019', numero: 19, norma: 'R.10.1.1.g', pregunta: 'Cálculo de campos electromagnéticos para asegurar que en espacios destinados a actividades rutinarias de las personas, no se superen los límites de exposición definidos en la Tabla 14.1.', valor_excel: 'N/A' },
        { id: 'DISENO-020', numero: 20, norma: 'R.10.1.1.h', pregunta: 'Cálculo de transformadores incluyendo los efectos de los armónicos y factor de potencia en la carga.', valor_excel: 'SI' },
        { id: 'DISENO-021', numero: 21, norma: 'R.10.1.1.i', pregunta: 'Cálculo del sistema de puesta a tierra.(aplica para subestaciones o cualquier tipo de malla) que contiene Cálculo y evaluación de tensiones de paso, contacto y transferidas)', valor_excel: 'SI' },
        { id: 'DISENO-022', numero: 22, norma: 'R.10.1.1.j', pregunta: 'Cálculo económico de conductores, teniendo en cuenta todos los factores de pérdidas, las cargas resultantes y los costos de la energía.(aplica para redes)', valor_excel: 'SI' },
        { id: 'DISENO-023', numero: 23, norma: 'R.10.1.1.k', pregunta: 'Verificación de los conductores, teniendo en cuenta el tiempo de disparo de los interruptores, la corriente de cortocircuito de la red y la capacidad de corriente del conductor de acuerdo con la norma  IEC 60909, IEEE 242, capítulo 9 o equivalente.', valor_excel: 'SI' },
        { id: 'DISENO-024', numero: 24, norma: 'R.10.1.1.l', pregunta: 'Cálculo mecánico de estructuras y de elementos de sujeción de equipos.', valor_excel: 'SI' },
        { id: 'DISENO-025', numero: 25, norma: 'R.10.1.1.m', pregunta: 'Cálculo y coordinación de protecciones contra sobrecorrientes. En baja tensión se permite la coordinación con las características de limitación de corriente de los dispositivos según IEC 60947-2 Anexo A.', valor_excel: 'SI' },
        { id: 'DISENO-026', numero: 26, norma: 'R.10.1.1.n', pregunta: 'Cálculos de canalizaciones (tubo, ductos, canaletas y electroductos) y volumen de encerramientos (cajas, tableros, conduletas, etc.)', valor_excel: 'SI' },
        { id: 'DISENO-027', numero: 27, norma: 'R.10.1.1.o', pregunta: 'Cálculos de pérdidas de energía, teniendo en cuenta los efectos de armónicos y factor de potencia. (aplica a redes)', valor_excel: 'SI' },
        { id: 'DISENO-028', numero: 28, norma: 'R.10.1.1.p', pregunta: 'Cálculos de regulación.', valor_excel: 'SI' },
        { id: 'DISENO-029', numero: 29, norma: 'R.10.1.1.q', pregunta: 'Clasificación de áreas.', valor_excel: 'N/A' },
        { id: 'DISENO-030', numero: 30, norma: 'R.10.1.1.r', pregunta: 'Elaboración de diagramas unifilares.', valor_excel: 'SI' },
        { id: 'DISENO-031', numero: 31, norma: 'R.10.1.1.s', pregunta: 'Elaboración de planos y esquemas eléctricos para construcción.', valor_excel: 'SI' },
        { id: 'DISENO-032', numero: 32, norma: 'R.10.1.1.t', pregunta: 'Especificaciones de construcción complementarias a los planos, incluyendo las de tipo técnico de equipos y materiales y sus condiciones particulares.', valor_excel: 'SI' },
        { id: 'DISENO-033', numero: 33, norma: 'R.10.1.1.u', pregunta: 'Establecer las distancias de seguridad requeridas.', valor_excel: 'SI' },
        { id: 'DISENO-034', numero: 34, norma: 'R.10.1.1.v', pregunta: 'Justificación técnica de desviación de la NTC 2050 cuando sea permitido, siempre y cuando no comprometa la seguridad de las personas o de la instalación.', valor_excel: 'N/A' },
        { id: 'DISENO-035', numero: 35, norma: 'R.10.1.1.w', pregunta: 'Los demás estudios que el tipo de instalación requiera para su correcta y segura operación, tales como condiciones sísmicas, acústicas, mecánicas o térmicas.', valor_excel: 'N/A' },
        { id: 'DISENO-036', numero: 36, norma: 'R.10.1.1', pregunta: 'Nota 2. El diseñador hace mención de aquellos ítems que a su juicio no apliquen.', valor_excel: 'SI' },
      ],
    },
    {
      id: 'DISENO_SIMPLIFICADO',
      titulo: '3. Diseño simplificado',
      preguntas: [
        { id: 'DISENO-037', numero: 37, norma: 'R.10.1.2.a', pregunta: 'Análisis de riesgos de origen eléctrico y medidas para mitigarlos.', valor_excel: 'N/A' },
        { id: 'DISENO-038', numero: 38, norma: 'R.10.1.2.a', pregunta: 'Cálculo y coordinación de protecciones contra sobrecorrientes.', valor_excel: 'N/A' },
        { id: 'DISENO-039', numero: 39, norma: 'R.10.1.2.a', pregunta: 'Diseño del sistema de puesta a tierra.', valor_excel: 'N/A' },
        { id: 'DISENO-040', numero: 40, norma: 'R.10.1.2.a', pregunta: 'Cálculos de canalizaciones y volumen de encerramientos (tubos, ductos, canaletas, electroductos).', valor_excel: 'N/A' },
        { id: 'DISENO-041', numero: 41, norma: 'R.10.1.2.a', pregunta: 'Cálculos de regulación', valor_excel: 'N/A' },
        { id: 'DISENO-042', numero: 42, norma: 'R.10.1.2.a', pregunta: 'Elaboración de planos y esquemas eléctricos para construcción.', valor_excel: 'N/A' },
        { id: 'DISENO-043', numero: 43, norma: 'R.10.1.2.a', pregunta: 'Elaboración de diagramas unifilares.', valor_excel: 'N/A' },
        { id: 'DISENO-044', numero: 44, norma: 'R.10.1.2.a', pregunta: 'Establecer las distancias de seguridad requeridas', valor_excel: 'N/A' },
        { id: 'DISENO-045', numero: 45, norma: 'R.10.1.2.b', pregunta: 'Análisis de riesgos de origen eléctrico y medidas para mitigarlos.', valor_excel: 'N/A' },
        { id: 'DISENO-046', numero: 46, norma: 'R.10.1.2.b', pregunta: 'Diseño de puesta a tierra.', valor_excel: 'N/A' },
        { id: 'DISENO-047', numero: 47, norma: 'R.10.1.2.b', pregunta: 'Protecciones  contra sobrecorriente y sobretensión.', valor_excel: 'N/A' },
        { id: 'DISENO-048', numero: 48, norma: 'R.10.1.2.b', pregunta: 'Elaboración de planos y esquemas eléctricos para construcción.', valor_excel: 'N/A' },
        { id: 'DISENO-049', numero: 49, norma: 'R.10.1.2.b', pregunta: 'Especificar  las distancias mínimas de seguridad requeridas', valor_excel: 'N/A' },
        { id: 'DISENO-050', numero: 50, norma: 'R.10.1.2.b', pregunta: 'Definir tensión mecánica máxima de conductores y templetes.', valor_excel: 'N/A' },
      ],
    },
    {
      id: 'REEMPLAZO_DISENO',
      titulo: '4. Reemplazo de Diseño',
      preguntas: [
        { id: 'DISENO-051', numero: 51, norma: 'R.10.1.3.a', pregunta: 'Cumplimiento de las distancias mínimas de seguridad a partes expuestas puestas de redes eléctricas y no se invaden servidumbres de líneas de transmisión', valor_excel: 'N/A' },
        { id: 'DISENO-052', numero: 52, norma: 'R.10.1.3.b', pregunta: 'El tipo y ubicación del sistema de puesta a tierra, especificando el tipo de electrodo, sus dimensiones así como el calibre y tipo del conductor de puesta a tierra', valor_excel: 'N/A' },
        { id: 'DISENO-053', numero: 53, norma: 'R.10.1.3.c', pregunta: 'Identificación de la capacidad y tipo de las protecciones de sobrecorriente, acorde con la carga y calibre del conductor de cada circuito', valor_excel: 'N/A' },
        { id: 'DISENO-054', numero: 54, norma: 'R.10.1.3.d', pregunta: 'Un diagrama unifilar de la instalación y el cuadro de carga de los circuitos (Aprobado por el operador de red)', valor_excel: 'N/A' },
        { id: 'DISENO-055', numero: 55, norma: 'R.10.1.3.e', pregunta: 'La localización de tablero de medición, tablero de distribución, tipo y diámetro de tubería, número y calibres de conductores, interruptores y tomacorrientes y demás aparatos involucrados en la instalación eléctrica', valor_excel: 'N/A' },
      ],
    },
  ],
  observaciones: { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
};

export default RETIE_DISENO_SCHEMA;