import { RETIEMasterSchema } from '../masterSchema';

export const RETIE_DISTRIBUCION_SCHEMA: RETIEMasterSchema = {
  hoja: 'DISTRIBUCIÓN',
  titulo: 'LISTA DE CHEQUEO DISTRIBUCIÓN',
  proceso: 'GESTIÓN DE INSPECCIÓN',
  codigo: 'F-GI-11',
  version: '2',
  fecha_formato: '01/08/2018',
  tipo_principal: 'checklist_distribucion_multipunto',
  instruccion_excel: 'Colocar X o ü según la evaluación a cada uno de los ítems',
  campos_contexto: [
    { id: 'codigo_servicio', label: 'Código servicio:', tipo: 'text' },
    { id: 'fecha_inspeccion', label: 'Fecha de la inspección:', tipo: 'date' },
    { id: 'fecha_cierre_no_conformidades', label: 'Fecha de cierre no conformidades:', tipo: 'text' },
  ],
  puntos_evaluacion: [
    { id: 'punto_1', label: 'Punto/Estructura 1' },
    { id: 'punto_2', label: 'Punto/Estructura 2' },
    { id: 'punto_3', label: 'Punto/Estructura 3' },
    { id: 'punto_4', label: 'Punto/Estructura 4' },
    { id: 'punto_5', label: 'Punto/Estructura 5' },
  ],
  respuesta_por_defecto: {
    visita_1: { tipo: 'radio', opciones: ['SI', 'NO', 'N.A'] },
    cierre: { tipo: 'radio', opciones: ['SI', 'NO'] },
  },
  secciones: [
    {
      id: 'HERRAJES',
      titulo: '1. HERRAJES',
      imagen_seccion: { id: 'distribucion_imagen_1', file: 'DISTRIBUCION_IMAGEN_1.png', rol: 'encabezado_seccion', descripcion: 'Encabezado sección Herrajes' },
      preguntas: [
        { id: 'DIST-001', numero: 1, norma: 'R. 25.5 a.', texto: 'Los herrajes usados en distribución cuentan con Certificado de Conformidad de Producto expedido por un organismo acreditado por el ONAC', required: true },
        { id: 'DIST-002', numero: 2, norma: 'R. 25.5 b.', texto: 'Los herrajes empleados en los circuitos de media tensión tienen un diseño adecuado a su función mecánica y eléctrica y resisten la acción corrosiva durante su vida útil', required: true },
        { id: 'DIST-003', numero: 3, norma: 'R. 25.7.1.b', texto: 'Los herrajes son los apropiados para el tipo, material y calibre de conductores', required: true },
        { id: 'DIST-004', numero: 4, norma: 'R. 25.5.d', texto: 'Las grapas de retención del conductor soportan un esfuerzo mecánico no menor al 80% de la carga de rotura del conductor', required: true },
      ],
    },
    {
      id: 'AISLADORES',
      titulo: '2. AISLADORES',
      imagen_seccion: { id: 'distribucion_imagen_2', file: 'DISTRIBUCION_IMAGEN_2.png', rol: 'encabezado_seccion', descripcion: 'Encabezado sección Aisladores' },
      preguntas: [
        { id: 'DIST-005', numero: 5, norma: 'R. 25.6.2', texto: 'Los aisladores usados en distribución demuestran el cumplimiento con el presente reglamento mediante un Certificado de Conformidad de Producto expedido por un organismo de certificación acreditado por el ONAC', required: true },
        { id: 'DIST-006', numero: 6, norma: 'R. 25.6.2.a', texto: 'Si el aislador es tipo disco la carga de rotura es de por lo menos el 80% de la tensión de rotura del conductor utilizado', required: true },
        { id: 'DIST-007', numero: 7, norma: 'R. 25.6.2.b', texto: 'Si el aislador es tipo carrete la carga de rotura es de por lo menos el 50% de la tensión de rotura del conductor utilizado', required: true },
        { id: 'DIST-008', numero: 8, norma: 'R. 25.6.2.c', texto: 'Si el aislador es tipo espigo (o equivalentes Line Post) la carga de rotura mínima equivale al 10% de la tensión de rotura del conductor utilizado', required: true },
        { id: 'DIST-009', numero: 9, norma: 'R. 25.6.2.d', texto: 'Si el aislador es tipo tensor la carga de rotura es superior a los esfuerzos mecánicos a que será sometido', required: true },
      ],
    },
    {
      id: 'REDES_AEREAS',
      titulo: '3. REDES DE DISTRIBUCIÓN AÉREAS',
      imagen_seccion: { id: 'distribucion_imagen_3', file: 'DISTRIBUCION_IMAGEN_3.png', rol: 'encabezado_seccion', descripcion: 'Encabezado sección Redes Aéreas' },
      preguntas: [
        { id: 'DIST-010', numero: 10, norma: 'R. 20.17.2.a', texto: 'Las crucetas de madera no se encuentran con fisuras', required: true },
        { id: 'DIST-011', numero: 11, norma: 'R. 25.7.1.d', texto: 'En áreas donde no se puedan garantizar las distancias de seguridad se instalaron conductores aislados', required: true },
        { id: 'DIST-012', numero: 12, norma: 'R. 25.7.1.f', texto: 'Los conectores o uniones entre conductores son de materiales apropiados para no producir pares galvánicos', required: true },
        { id: 'DIST-013', numero: 13, norma: 'R. 25.7.1.g', texto: 'No se observa deterioro de los conductores', required: true },
        { id: 'DIST-014', numero: 14, norma: 'R. 25.7.1.a', texto: 'Los conductores no son sometidos a tensiones mecánicas por encima de las especificadas', required: true },
        { id: 'DIST-015', numero: 15, norma: 'R. 25.7.1.c', texto: 'Los conductores tienen el calibre mínimo reglamentado según el nivel de tensión', required: true },
        { id: 'DIST-016', numero: 16, norma: 'R. 25.7.1.e', texto: 'Las flechas de los conductores se ajustan a la tabla de tendido para las condiciones de temperatura y vano', required: true },
        { id: 'DIST-017', numero: 17, norma: 'R. 25.7.1.h', texto: 'Se identifican los conductores de neutro con color blanco o con marcas en franjas blancas', required: true },
        { id: 'DIST-018', numero: 18, norma: 'R. 25.7.1.i', texto: 'Los conductores desnudos de neutro en redes aéreas están conectados a tierra en los extremos de los circuitos', required: true },
        {
          id: 'DIST-026',
          numero: 19,
          norma: 'R. 25.7.1.j / Tabla RETIE',
          texto: 'Las distancias de seguridad entre conductores y objetos, edificaciones, suelos y líneas cumplen con los valores mínimos del RETIE',
          tipo_especial: 'distancias_seguridad',
          required: true,
          campos_distancia: [
            { id: 'dist_a', label: 'a (m)', descripcion: 'Distancia vertical al suelo (zona residencial/comercial)' },
            { id: 'dist_b', label: 'b (m)', descripcion: 'Distancia vertical al suelo (vía pública)' },
            { id: 'dist_c', label: 'c (m)', descripcion: 'Distancia horizontal a edificaciones' },
            { id: 'dist_d', label: 'd (m)', descripcion: 'Distancia entre conductores en cruce' },
            { id: 'dist_d1', label: 'd1 (m)', descripcion: 'Distancia mínima en retenidas' },
            { id: 'dist_e', label: 'e (m)', descripcion: 'Distancia a arborización' },
          ],
          recursos_visuales: [
            { id: 'distribucion_imagen_4', file: 'DISTRIBUCION_IMAGEN_4.png', descripcion: 'Diagrama de distancias de seguridad - Vista A' },
            { id: 'distribucion_imagen_6', file: 'DISTRIBUCION_IMAGEN_6.png', descripcion: 'Diagrama de distancias de seguridad - Vista B' },
            { id: 'distribucion_imagen_7', file: 'DISTRIBUCION_IMAGEN_7.png', descripcion: 'Diagrama de distancias de seguridad - Vista C' },
          ],
        },
      ],
    },
    {
      id: 'POSTES',
      titulo: '4. POSTES',
      preguntas: [
        { id: 'DIST-019', numero: 20, norma: 'R. 20.17.1.l', texto: 'Los postes y torrecillas llevan placa visible con información técnica', required: true },
        { id: 'DIST-020', numero: 21, norma: 'R. 25.4.a / R. 20.17.1.a', texto: 'Se utilizan postes o estructuras con dimensiones y carga de rotura estandarizadas', required: true },
        { id: 'DIST-021', numero: 22, norma: 'R. 20.17.1.b', texto: 'Los postes de materiales distintos a madera son especificados y probados para cargas de rotura mínimas', required: true },
        { id: 'DIST-022', numero: 23, norma: 'R. 25.4.c', texto: 'Los postes, torres o torrecillas están protegidos contra la corrosión y están sólidamente puestos a tierra', required: true },
        { id: 'DIST-023', numero: 24, norma: 'R. 25.4.b', texto: 'Los postes de madera y elementos de madera no presentan hongos ni agentes degradantes', required: true },
        { id: 'DIST-024', numero: 25, norma: 'R. 25.4.f', texto: 'Los postes o estructuras en suspensión fabricados en materiales sintéticos cumplen resistencia mínima requerida', required: true },
        { id: 'DIST-025', numero: 26, norma: 'R. 25.4.g', texto: 'En zonas no interconectadas se permite instalación de postes construidos en sitio bajo declaración del proveedor', required: true },
        { id: 'DIST-027', numero: 27, norma: 'R. 25.4.e / R. 20.17.1', texto: 'Los postes no presentan fisuras u otros deterioros que comprometan las condiciones mecánicas', required: true },
        { id: 'DIST-028', numero: 28, norma: 'R. 20.17.2.d', texto: 'Los postes se encuentran empotrados a la profundidad reglamentaria', required: true },
        { id: 'DIST-029', numero: 29, norma: 'R. 20.17.2.d', texto: 'Los postes no presentan peligro de volcamiento', required: true },
        { id: 'DIST-030', numero: 30, norma: 'R. 20.2', texto: 'El templete cumple con las características técnicas de instalación', required: true },
      ],
    },
    {
      id: 'TRANSICIONES',
      titulo: '5. TRANSICIONES REDES MT A CABLE AISLADO',
      preguntas: [
        { id: 'DIST-031', numero: 31, norma: 'R. 20.14.2.a', texto: 'A las transiciones de redes aéreas de MT a cable aislado le fueron instaladas DPS', required: true },
        { id: 'DIST-032', numero: 32, norma: 'R. 27.3.a', texto: 'La tubería metálica para transiciones de red tiene instalado capacete o elemento que impide entrada de agua', required: true },
        { id: 'DIST-033', numero: 33, norma: 'R. 27.3.a', texto: 'El tubo es galvanizado tipo intermedio o pesado', required: true },
        { id: 'DIST-034', numero: 34, norma: 'R. 20.6.a', texto: 'La tubería metálica para transiciones de red se identificó con franjas color naranja', required: true },
        { id: 'DIST-035', numero: 35, norma: 'N. 300-24', texto: 'En tubos conduit con conductores superiores a 1 kV se indica nivel de tensión y advertencia de peligro', required: true },
      ],
    },
    {
      id: 'SUBTERRANEAS',
      titulo: '6. REDES DE DISTRIBUCIÓN SUBTERRÁNEAS',
      preguntas: [
        { id: 'DIST-036', numero: 36, norma: 'R. 25.7.2.l', texto: 'Todas las transiciones entre tipos de cables y derivaciones se realizan en cámaras o cajas de inspección', required: true },
        { id: 'DIST-037', numero: 37, norma: 'R. 25.7.2.o', texto: 'Los empalmes y derivaciones de los conductores son accesibles', required: true },
        { id: 'DIST-038', numero: 38, norma: 'R. 25.7.2.a', texto: 'Las canalizaciones o ductos no deterioran el aislamiento de los conductores', required: true },
        { id: 'DIST-039', numero: 39, norma: 'R. 25.7.2.n', texto: 'El circuito y sus fases están debidamente identificados en cámaras de inspección', required: true },
        { id: 'DIST-040', numero: 40, norma: 'R. 6.3', texto: 'Los conductores aislados están identificados con código de colores', required: true },
        { id: 'DIST-041', numero: 41, norma: 'R. 25.7.2.c', texto: 'Se mantiene distancia útil mínima entre conductor y otros servicios', required: true },
        { id: 'DIST-042', numero: 42, norma: 'R. 25.7.2.i', texto: 'Todos los conductores del circuito se instalan en el mismo ducto', required: true },
        { id: 'DIST-043', numero: 43, norma: 'R. 25.7.2.i', texto: 'Si no caben los conductores en un ducto se utilizan ductos paralelos cercanos', required: true },
        { id: 'DIST-044', numero: 44, norma: 'N. 300-32', texto: 'Conductores menores de 600V no están instalados con conductores mayores de 600V', required: true },
        { id: 'DIST-045', numero: 45, norma: 'N. 710.b.4', texto: 'Las canalizaciones que entran a edificaciones están selladas', required: true },
        { id: 'DIST-046', numero: 46, norma: 'R. 25.7.2.p', texto: 'Las uniones entre conductores aseguran máxima hermeticidad', required: true },
        {
          id: 'DIST-047',
          numero: 47,
          norma: 'R. 25.7.2.f',
          texto: 'La profundidad de enterramiento cumple valores mínimos RETIE',
          tipo_especial: 'profundidad_enterramiento',
          required: true,
          recursos_visuales: [
            { id: 'distribucion_imagen_5', file: 'DISTRIBUCION_IMAGEN_5.png', descripcion: 'Tabla RETIE de profundidades mínimas de enterramiento de conductores subterráneos' },
          ],
        },
        { id: 'DIST-048', numero: 48, norma: 'R. 25.7.2.p', texto: 'Cuando se utilizan ductos metálicos estos son galvanizados y conectados a tierra', required: true },
        { id: 'DIST-049', numero: 49, norma: 'R. 25.7.2.h', texto: 'Los cables subterráneos instalados debajo de construcciones están alojados en ducto', required: true },
        { id: 'DIST-050', numero: 50, norma: 'R. 25.7.2.j', texto: 'Las canalizaciones subterráneas tienen cámaras de inspección', required: true },
        { id: 'DIST-051', numero: 51, norma: 'R. 25.7.2.e', texto: 'No se instalan cables sobre el nivel del suelo terminado', required: true },
        { id: 'DIST-052', numero: 52, norma: 'R. 25.7.2.k', texto: 'El fondo de la zanja es firme y libre de obstáculos', required: true },
        { id: 'DIST-053', numero: 53, norma: 'R. 25.7.2.k', texto: 'Los cables cuentan con barrera de protección mecánica', required: true },
        { id: 'DIST-054', numero: 54, norma: 'R. 25.7.2.k', texto: 'Se instalaron cintas de identificación sobre cables enterrados', required: true },
        { id: 'DIST-055', numero: 55, norma: 'R. 25.7.2.q', texto: 'El uso de conductores de aluminio cumple requisitos RETIE', required: true },
      ],
    },
    {
      id: 'REQUISITOS_GENERALES',
      titulo: '7. REQUISITOS GENERALES Y SPT',
      preguntas: [
        { id: 'DIST-056', numero: 56, norma: 'R. 25.2.a', texto: 'El proyecto cuenta con diseño, memorias de cálculo y planos', required: true },
        { id: 'DIST-057', numero: 57, norma: 'N. 110-3.b', texto: 'Los productos eléctricos fueron instalados para fines certificados', required: true },
        { id: 'DIST-058', numero: 58, norma: 'N. 110-12', texto: 'Los equipos eléctricos fueron instalados de manera limpia y profesional', required: true },
        { id: 'DIST-059', numero: 59, norma: 'R. 2.1', texto: 'La instalación se encuentra finalmente construida', required: true },
        { id: 'DIST-060', numero: 60, norma: 'N. 300-4', texto: 'Los conductores eléctricos están protegidos contra daños físicos', required: true },
        { id: 'DIST-061', numero: 61, norma: 'R. 25.2.b', texto: 'Existe registro de pruebas técnicas y mantenimiento', required: true },
        { id: 'DIST-062', numero: 62, norma: 'R. 15.1', texto: 'Existe caja de inspección accesible del SPT', required: true },
        { id: 'DIST-063', numero: 63, norma: 'R. 15.3.1.i', texto: 'Cada electrodo está enterrado totalmente', required: true },
        { id: 'DIST-064', numero: 64, norma: 'R. 15.3.1.a', texto: 'La construcción del SPT utiliza electrodos permitidos', required: true },
        { id: 'DIST-065', numero: 65, norma: 'R. 15.3.1.b', texto: 'No se utiliza aluminio en electrodos de puesta a tierra', required: true },
        { id: 'DIST-066', numero: 66, norma: 'R. 15.3.1.f', texto: 'El electrodo tipo varilla tiene mínimo 2.4 m', required: true },
        { id: 'DIST-067', numero: 67, norma: 'R. 15.1', texto: 'Las conexiones del SPT enterradas utilizan soldadura exotérmica', required: true },
        { id: 'DIST-068', numero: 68, norma: 'R. 6.3', texto: 'Los conductores de tierra son verdes o desnudos', required: true },
        { id: 'DIST-069', numero: 69, norma: 'N. 250-118', texto: 'Toda conexión del SPT está limpia', required: true },
        { id: 'DIST-070', numero: 70, norma: 'R. 15', texto: 'Los apoyos o estructuras metálicas están puestos a tierra', required: true },
        { id: 'DIST-071', numero: 71, norma: 'R. 25.3.a', texto: 'El sistema de puesta a tierra cumple criterios RETIE', required: true },
        { id: 'DIST-072', numero: 72, norma: 'R. 25.3.b', texto: 'Los diseñadores consideraron máxima corriente de falla a tierra esperada', required: true },
      ],
    },
    {
      id: 'OBSERVACIONES',
      titulo: 'OBSERVACIONES',
      preguntas: [
        { id: 'DIST-OBS', numero: null, texto: 'Observaciones generales', tipo: 'textarea', required: false },
      ],
    },
  ],
} as unknown as RETIEMasterSchema;

export default RETIE_DISTRIBUCION_SCHEMA;