export const RETIE_IN_SCHEMA = {
  hoja: 'IN',
  titulo: 'INFORMACIÓN GENERAL / ÍNDICE Y RESUMEN DEL SERVICIO',
  tipo_principal: 'indice_resumen_servicio',
  campos_contexto: [
    { id: 'codigo_servicio', label: 'CODIGO DEL SERVICIO', tipo: 'text', valor_excel: 'R&F-0467-10-20' },
    { id: 'fecha_inspeccion', label: 'Fecha de la inspección:', tipo: 'date', valor_excel: '2020-10-29T00:00:00' },
    { id: 'fecha_cierre_no_conformidades', label: 'Fecha de cierre deno conformidades:', tipo: 'text', valor_excel: 'N/A' },
  ],
  modulos: [
    { id: 'IN-MOD-01', descripcion: 'Uso final residencial', caracteristicas_acometida: true },
    { id: 'IN-MOD-02', descripcion: 'Uso final industrial y comercial' },
    { id: 'IN-MOD-03', descripcion: 'Alta concentración de personas, sistemas de emergencia y bombas contra incendios' },
    { id: 'IN-MOD-04', descripcion: 'Apantallamiento' },
    { id: 'IN-MOD-05', descripcion: 'Ascensores' },
    { id: 'IN-MOD-06', descripcion: 'Piscinas' },
    { id: 'IN-MOD-07', descripcion: 'Distribución' },
    { id: 'IN-MOD-08', descripcion: 'Subestación tipo poste' },
    { id: 'IN-MOD-09', descripcion: 'Subestación tipo pedestal' },
    { id: 'IN-MOD-10', descripcion: 'Subestación tipo interior' },
    { id: 'IN-MOD-11', descripcion: 'Subestación tipo patio' },
  ],
  aislamiento: [
    { id: 'IN-AIS-01', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 401 C', fases: '1' },
    { id: 'IN-AIS-02', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 402 C', fases: '1' },
    { id: 'IN-AIS-03', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 403 C', fases: '1' },
    { id: 'IN-AIS-04', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 404 C', fases: '1' },
    { id: 'IN-AIS-05', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 501 C', fases: '1' },
    { id: 'IN-AIS-06', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 502 C', fases: '1' },
    { id: 'IN-AIS-07', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 503 C', fases: '1' },
    { id: 'IN-AIS-08', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 504 C', fases: '1' },
    { id: 'IN-AIS-09', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 601 C', fases: '1' },
    { id: 'IN-AIS-10', lugar: 'CIRCUITO ALIMENTADOR APARTAMENTO 602 C', fases: '1' },
    { id: 'IN-AIS-11', lugar: 'CIRCUITO ALIMENTADOR ZONAS COMUNES', fases: '3' },
  ],
  iluminancia: [
    { id: 'IN-ILUM-01', lugar: 'Frente a Apto 101' },
    { id: 'IN-ILUM-02', lugar: 'frente a Apto 102' },
    { id: 'IN-ILUM-03', lugar: 'Escaleras piso 1-2' },
    { id: 'IN-ILUM-04', lugar: 'Entre Aptos 201 y 202' },
    { id: 'IN-ILUM-05', lugar: 'Entre Aptos 203 y 204' },
    { id: 'IN-ILUM-06', lugar: 'Escaleras piso 2-3' },
    { id: 'IN-ILUM-07', lugar: 'Entre Aptos 301 y 302' },
    { id: 'IN-ILUM-08', lugar: 'Entre Aptos 303 y 304' },
    { id: 'IN-ILUM-09', lugar: 'Escaleras piso 3 - 4' },
    { id: 'IN-ILUM-10', lugar: 'Entre Aptos 401 y 402' },
    { id: 'IN-ILUM-11', lugar: 'Entre Aptos 403 y 404' },
    { id: 'IN-ILUM-12', lugar: 'Escaleras piso 4 - 5' },
    { id: 'IN-ILUM-13', lugar: 'Entre Aptos 501 y 502' },
    { id: 'IN-ILUM-14', lugar: 'Entre Aptos 503 y 504' },
    { id: 'IN-ILUM-15', lugar: 'Escaleras piso 5 - 6' },
    { id: 'IN-ILUM-16', lugar: 'Entre Aptos 601 y 602' },
  ],
};

export default RETIE_IN_SCHEMA;