export const RETIE_UFIYC_SCHEMA = {
  hoja: 'UF I Y C',
  titulo: 'LISTA DE CHEQUEO USO FINAL INDUSTRIAL Y COMERCIAL',
  proceso: 'GESTION DE INSPECCION',
  codigo: 'F-GI-06',
  version: '2',
  fecha_formato: '09/30/2020',
  instruccion_excel: 'Colocar X o ü según la evaluación a cada uno de los ítems',
  campos_contexto: [
    { id: 'codigo_servicio', label: '', tipo: 'text', valor_excel: '' },
    { id: 'fecha_inspeccion', label: '', tipo: 'date', valor_excel: '' },
    { id: 'fecha_cierre_no_conformidades', label: '', tipo: 'text', valor_excel: '' },
  ],
  secciones: [
    {
      id: '1__Requisitos_generales_de_acometida',
      titulo: '1. Requisitos generales de acometida',
      preguntas: [
        { id: 'UFIC-001', numero: 1, norma: 'N. 230-2.a', pregunta: 'El edificio u otra estructura a la que llegue la corriente eléctrica tiene solo una acometida.', valor_excel: '' },
        { id: 'UFIC-002', numero: 2, norma: 'N. 230-2.b', pregunta: 'Si el edificio esta alimentado por más de un circuito o por una combinación de circuitos alimentadores y acometidas, en cada lugar de desconexión y cada ramal se instala una placa.', valor_excel: '' },
        { id: 'UFIC-003', numero: 3, norma: 'N. 230-3', pregunta: 'Los conductores de acometida NO pasan a través del interior de otro edificio o estructura.', valor_excel: '' },
        { id: 'UFIC-004', numero: 4, norma: 'N. 230-7', pregunta: 'Los conductores que no sean los de acometida no están instalados en la misma canalización de la acometida', valor_excel: '' },
        { id: 'UFIC-005', numero: 5, norma: 'R. 27.3 b.', pregunta: 'En instalaciones monofásicas de capacidad instalable ≤ a 3 kVA el cable de acometida es de calibre no menor a 10 AWG', valor_excel: '' },
        { id: 'UFIC-006', numero: 6, norma: 'R. 27.3 b.', pregunta: 'En instalaciones de capacidad instalable entre 3 kVA y 10 kVA el cable de acometida es de calibre no menor a 8 AWG', valor_excel: '' },
        { id: 'UFIC-007', numero: 7, norma: 'R. 27.3 b.', pregunta: 'Si el cable de acometida es de aluminio, es de la serie AA8000 y la seccion es dos calibres mayor a la del conductor de cobre', valor_excel: '' },
        { id: 'UFIC-008', numero: 8, norma: 'R. 27.3.c.', pregunta: 'La regulación de tensión en la acometida no supera el 3%.', valor_excel: '' },
        { id: 'UFIC-009', numero: 9, norma: 'R. 27.3 d.', pregunta: 'En la fachada NO existen conductores a la vista, ni incrustados directamente. Los cables que lleguen a la caja del medidor estan encerrados en tubería metálica incrustada y en donde por limitaciones de los materiales de las paredes no se pueda hacer la incrustación, la canalización es certificada para intemperie y a prueba de impacto no menor al de la tubería tipo IMC.', valor_excel: '' },
        { id: 'UFIC-010', numero: 10, norma: 'R. 27.3 d.', pregunta: 'Se aceptarán cables a la vista sólo si el cable de la acometida es tipo concéntrico con cubierta XLPE o HDPE, no presenta bucles que generen contaminación visual', valor_excel: '' },
        { id: 'UFIC-011', numero: 11, norma: 'N. 230-46 R. 27.3 f.', pregunta: 'Los conductores de acometida NO presentan empalmes. Se acepta si se utiliza un procedimiento técnico aprobado por el O.R.', valor_excel: '' },
        { id: 'UFIC-012', numero: 12, norma: 'N.230-202.a', pregunta: 'La acometida de más de 600 V nominales, no son de calibre menor a 6 AWG, excepto en cables de varios conductores, los cuales no son menores a 8 AWG', valor_excel: '' },
        { id: 'UFIC-013', numero: 13, norma: 'N.230-203', pregunta: 'La acometida de más de 600 V nominales, en lugares en los que las personas puedan entrar en contacto con partes energizadas, hay avisos con las palabras “Peligro, Alta tensión, Manténgase alejado”.', valor_excel: '' },
      ],
    },
    {
      id: '2__Acometida',
      titulo: '2. Acometida',
      preguntas: [
        { id: 'UFIC-014', numero: 14, norma: 'R. 27.3. a.', pregunta: 'El tubo es galvanizado tipo intermedio o pesado y tiene capacete o elemento que impida el paso de agua.', valor_excel: '' },
        { id: 'UFIC-015', numero: 15, norma: 'R.27.3.e N.230-54.f', pregunta: 'Se forma un bucle de goteo independiente en cada conductor. Se evita que la acometida se convierta en canal de transporte de agua lluvia a la fachada o al equipo de medida.', valor_excel: '' },
        { id: 'UFIC-016', numero: 16, norma: 'R. 27.3. a.', pregunta: 'El tubo o poste permite el anclaje de una percha o gancho de sujeción de los cables de acometida', valor_excel: '' },
        { id: 'UFIC-017', numero: 17, norma: 'R. 27.3. a.', pregunta: 'El tubo está fijado mecánicamente con templetes, o apoyos debidamente empotrados que no generen riesgos de volcamiento o rotura.', valor_excel: '' },
        { id: 'UFIC-018', numero: 18, norma: 'R. 20.6.a', pregunta: 'La canalización que esta expuesta o a la vista tiene franjas de color naranja de al menos 10 cm de anchas.', valor_excel: '' },
        { id: 'UFIC-019', numero: 19, norma: 'R. 27.3 a.', pregunta: 'Los cables de acometida AEREA están sujetos tanto a la estructura de soporte de la red de uso general como a la edificación a alimentar.', valor_excel: '' },
        { id: 'UFIC-020', numero: 20, norma: 'N.230-22', pregunta: 'Los conductores de acometida soportan la exposición a los agentes atmosféricos y otras condiciones de uso sin que se produzcan fugas perjudiciales de corriente. Los conductores individuales esta aislados con un material termoplástico extruido o aislante termo ajustable.', valor_excel: '' },
        { id: 'UFIC-021', numero: 21, norma: 'R. 27.3 b.', pregunta: 'El cable de acometida aerea es del tipo antifraude como el concéntrico, o trenzado.', valor_excel: '' },
        { id: 'UFIC-022', numero: 22, norma: 'R. 27.3 a N 230-24.b.4', pregunta: 'La altura de la acometida no es menor a 5,5 m (cruce de vías).', valor_excel: '' },
        { id: 'UFIC-023', numero: 23, norma: 'N.230-24 a.', pregunta: 'Los tramos aéreos de conductores a la vista y cables a la vista de varios conductores de no más de 600 V nominales, estan a una distancia vertical no menor a 2,5 m desde la superficie del tejado hacia arriba. La distancia vertical sobre el nivel del tejado se debe mantener para una distancia de no menos de 0,9 m desde el borde del tejado,  en todas las direcciones.', valor_excel: '' },
        { id: 'UFIC-024', numero: 24, norma: 'N.230-24.b', pregunta: 'Los conductores aéreos de acometida de no más de 600 V nominales,  guardan la siguiente distancia mínima medida desde la superficie acabada del suelo: -1) 3,0 m en la acometida de la edificación, también en el punto más bajo del bucle de goteo de la entrada eléctrica al edificio y sobre las zonas o aceras accesibles sólo a los peatones y limitado a 150 V a tierra. -2) 3,6 m sobre edificios residenciales y accesos vehiculares y sobre las zonas comerciales no sujetas a tráfico de camiones, cuando la tensión esté limitada a 300 V a tierra. -3) 4,6 m en las zonas mencionadas en el punjo anterior .2), cuando la tensión supere los 300 V a tierra.', valor_excel: '' },
        { id: 'UFIC-025', numero: 25, norma: 'N.230-8', pregunta: '(cajas)-Sellado de las canalizaciones . Cuando una canalización de acometida entre desde la red de distribución SUBTERRANEA, esta sellada. También estan selladas las canalizaciones libres o no utilizadas.', valor_excel: '' },
        { id: 'UFIC-026', numero: 26, norma: 'N.230-30', pregunta: 'Los conductores subterráneos de entrada de acometida son aislados para la tensión correspondiente.', valor_excel: '' },
        { id: 'UFIC-027', numero: 27, norma: 'N. 300-5.a.', pregunta: 'Se cumple la distancia mínima de enterramiento para acometida subterránea.(Tabla 300-5)', valor_excel: '' },
      ],
    },
    {
      id: '3__Armario_de_medidores',
      titulo: '3. Armario de medidores',
      preguntas: [
        { id: 'UFIC-028', numero: 28, norma: 'N. 110-34. a', pregunta: 'El espacio de trabajo alrededor del equipo eléctrico (más de 600 V) se cumple, según Artículo 110-34', valor_excel: '' },
        { id: 'UFIC-029', numero: 29, norma: 'N. 110-16. a', pregunta: 'El espacio de trabajo alrededor del equipo eléctrico (600 V o menos) se cumple, según Artículo 110-16', valor_excel: '' },
        { id: 'UFIC-030', numero: 30, norma: 'N. 110-16. a) 2)', pregunta: 'La puerta abre por lo menos 90°', valor_excel: '' },
        { id: 'UFIC-031', numero: 31, norma: 'N.384-4. a) 1) N.110-16 .f) 1)', pregunta: 'En paneles de distribucion y centros de control de motores ubicados en interiores se cumple espacio dedicado,en esta zona no se debe ubicar tuberia, ductos o equipos ajenos, se permiten rociadores. Para la instalacion se dispone de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta una altura de 7,6 m o hasta el techo', valor_excel: '' },
        { id: 'UFIC-032', numero: 32, norma: 'N. 110-16. d', pregunta: 'Existe iluminación en todos los espacios de trabajo alrededor de los equipos de acometida, tableros de distribución o centros de control de motores. No es necesario elementos adicionales si la iluminación proviene de fuente adyacente. (600 V o menos)', valor_excel: '' },
        { id: 'UFIC-033', numero: 33, norma: 'N. 110-16. d', pregunta: 'En los cuartos de equipos eléctricos, la iluminación no es accionada exclusivamente por medios automáticos (600 V o menos)', valor_excel: '' },
        { id: 'UFIC-034', numero: 34, norma: 'N. 110-34. d', pregunta: 'Hay iluminación con una intensidad mínima de 100 luxes alrededor de equipos eléctricos(más de 600 V)', valor_excel: '' },
        { id: 'UFIC-035', numero: 35, norma: 'N. 110-34. d', pregunta: 'Las salidas para alumbrado estan dispuestas de manera que las personas que cambien las bombillas o hagan reparaciones en el sistema de alumbrado, no corran peligro por las partes u otros equipos energizados. (más de 600 V)', valor_excel: '' },
        { id: 'UFIC-036', numero: 36, norma: 'N. 110-34. d', pregunta: 'Los puntos de mando están situados de modo que no sea probable que las personas entren en contacto con ninguna parte energizada o móvil del equipo cuando vayan a encender el alumbrado.  (más de 600 V)', valor_excel: '' },
        { id: 'UFIC-037', numero: 37, norma: 'N.110-16.c', pregunta: 'El cuarto que contenga un equipo eléctrico de corriente nominal mayor a 1200 A y de más de 1,8 m de ancho ,tiene una entrada de por lo menos 0,6 m de ancho y de 1,90 m de alto', valor_excel: '' },
        { id: 'UFIC-038', numero: 38, norma: 'R.20.23.1.4.f', pregunta: 'El armario tiene logo de riesgo eléctrico, señalización de seguridad e identificación.', valor_excel: '' },
        { id: 'UFIC-039', numero: 39, norma: 'R.20.23.1.4. a-e', pregunta: 'El armario tiene adherida de manera clara, permanente y visible placa con características técnicas.', valor_excel: '' },
        { id: 'UFIC-040', numero: 40, norma: 'R.20.23.1.4.g,i', pregunta: 'El armario tiene cuadro para identificar circuitos y diagrama unifilar actualizado.', valor_excel: '' },
        { id: 'UFIC-041', numero: 41, norma: 'R. 27.3.d', pregunta: 'Los cables que lleguen a la caja del medidor están encerrados en tubería metálica incrustada', valor_excel: '' },
        { id: 'UFIC-042', numero: 42, norma: 'N. 230-74 N. 230-78', pregunta: 'Existe un medio para desconectar todos los conductores a partir de los conductores de acometida (Protección principal).Es accionable desde fuera', valor_excel: '' },
        { id: 'UFIC-043', numero: 43, norma: 'R.27.4.3.a,b', pregunta: 'La protección principal es automática y protege contra sobrecorriente.', valor_excel: '' },
        { id: 'UFIC-044', numero: 44, norma: 'R.20.16.2.2.b', pregunta: 'Un interruptor automático tiene especificaciones de corriente y tensión, no menores a los valores nominales de los circuitos que controla.', valor_excel: '' },
        { id: 'UFIC-045', numero: 45, norma: 'R.20.16.2.2. a', pregunta: 'En los interruptores automáticos el circuito alimentador llegue al terminal de línea y la salida se conecte a los terminales de carga.', valor_excel: '' },
        { id: 'UFIC-046', numero: 46, norma: 'R.27.4.3.c.', pregunta: 'La capacidad de corriente del cable de acometida es superior a la capacidad de la protección asociada.', valor_excel: '' },
        { id: 'UFIC-047', numero: 47, norma: 'N.230-66  N.230-70.b', pregunta: 'El equipo de acometida y todos los medios de desconexión esta rotulado para su uso.', valor_excel: '' },
        { id: 'UFIC-048', numero: 48, norma: 'R.20.23.1.3.f', pregunta: 'El alambrado, cableado (cable de acometida, barrajes, circuitos alimentadores) cumple el código de colores.', valor_excel: '' },
        { id: 'UFIC-049', numero: 49, norma: 'N.384-3. f) R. 20.23.1.2.d', pregunta: 'Cableado-barrajes cumplen disposición de las fases; A, B, C, de frente a posterior; superior a inferior, o de izquierda a derecha, vista desde el frente del tablero.', valor_excel: '' },
        { id: 'UFIC-050', numero: 50, norma: 'R.20.23.4.k', pregunta: 'Cuando la conexión involucra varias barras por fase, los conectores se deben colocar enfrentados y con espaciadores de cobre entre las barras', valor_excel: '' },
        { id: 'UFIC-051', numero: 51, norma: 'R.20.23.1.3.d', pregunta: 'El armario cuenta con barrajes de tierra y neutro con suficientes terminales de salida.', valor_excel: '' },
        { id: 'UFIC-052', numero: 52, norma: 'N.230-65', pregunta: 'El equipo de acometida es adecuado para la corriente de corto circuito', valor_excel: '' },
        { id: 'UFIC-053', numero: 53, norma: 'R.20.23.4.c', pregunta: 'En los tableros con sistema de instalación tipo Riel DIN no se supera el nivel de ocupación definido por el productor', valor_excel: '' },
        { id: 'UFIC-054', numero: 54, norma: 'R.20.16.2.2.h', pregunta: 'Los dispositivos de protección contra sobre corriente son fácilmente accesibles', valor_excel: '' },
        { id: 'UFIC-055', numero: 55, norma: 'R.20.16.2.2.c', pregunta: 'Los dispositivos de interrupción de corriente por fuga a tierra, pueden ir incorporados en los interruptores automáticos o ubicados al lado del mismo formando un conjunto dentro del panel o tablero que los contiene', valor_excel: '' },
        { id: 'UFIC-056', numero: 56, norma: 'R. 20.5.2.f', pregunta: 'Las aberturas no utilizadas están cerradas eficazmente', valor_excel: '' },
        { id: 'UFIC-057', numero: 57, norma: 'N.310-3', pregunta: 'Los conductores con sección transversal 8 AWG y mayor instalados en canalizaciones son cableados.', valor_excel: '' },
        { id: 'UFIC-058', numero: 58, norma: 'R. 20.23.4.j', pregunta: 'Para cable de aluminio, tiene conector bimetálico, se utiliza gel retardante a la oxidación.', valor_excel: '' },
        { id: 'UFIC-059', numero: 59, norma: 'R. 20.23.1.3.a', pregunta: 'Los conductores instalados en el tablero, se conectan mediante terminal.', valor_excel: '' },
        { id: 'UFIC-060', numero: 60, norma: 'R.20.12.2.a', pregunta: 'No se instala dos o más conectores o terminales en la misma bornera o al mismo tornillo.', valor_excel: '' },
        { id: 'UFIC-061', numero: 61, norma: 'N.310-4', pregunta: 'Los conductores de fase, neutro o el conductor puesto a tierra, de sección transversal menor a 1/0 AWG, "NO" están conectados en paralelo.', valor_excel: '' },
        { id: 'UFIC-062', numero: 62, norma: 'R. 15.3.3. d', pregunta: 'El conductor de puesta a tierra de equipos acompaña los conductores activos durante todo su recorrido y por la misma canalizacion', valor_excel: '' },
        { id: 'UFIC-063', numero: 63, norma: 'N. 250-95', pregunta: 'El conductor de tierra de cada circuito alimentador cumple el calibre mínimo dado en la tabla 250-95', valor_excel: '' },
        { id: 'UFIC-064', numero: 64, norma: 'R. 27.4.3.c', pregunta: 'La capacidad de corriente del conductor de fase es superior a la capacidad de la protección asociada para cada circuito. Ver tabla 310-16 NTC 2050', valor_excel: '' },
        { id: 'UFIC-065', numero: 65, norma: 'R. 27.4.', pregunta: 'El conductor neutro y el de puesta a tierra son independientes entre sí y se conectan con un puente equipotencial, donde está la protección principal', valor_excel: '' },
        { id: 'UFIC-066', numero: 66, norma: 'N.250-79.d N.250-53.b', pregunta: 'El puente de conexión equipotencial no es de menor calibre que el establecido en la Tabla 250-94 y sin empalmes', valor_excel: '' },
        { id: 'UFIC-067', numero: 67, norma: 'N. 373-8', pregunta: 'No existen empalmes dentro del armario.', valor_excel: '' },
        { id: 'UFIC-068', numero: 68, norma: 'R. 20.23.4.g', pregunta: 'Los cables NO atraviesan los barrajes', valor_excel: '' },
      ],
    },
    {
      id: '4__SPT',
      titulo: '4. SPT',
      preguntas: [
        { id: 'UFIC-069', numero: 69, norma: '27.4.2.b', pregunta: 'La instalación eléctrica dispone de un sistema de puesta a tierra', valor_excel: '' },
        { id: 'UFIC-070', numero: 70, norma: 'R. 15.1.', pregunta: 'Existe caja de inspección SPT, es de mínimo 30 cm x 30 cm, o de 30 cm de diámetro si es circular y la tapa es removible.', valor_excel: '' },
        { id: 'UFIC-071', numero: 71, norma: 'R. 15.3.1.i', pregunta: 'Cada electrodo está enterrado en su totalidad y la parte superior del electrodo enterrado queda a mínimo 15 cm de la superficie.', valor_excel: '' },
        { id: 'UFIC-072', numero: 72, norma: 'N.250-118', pregunta: 'Toda conexión del SPT está limpia (de cemento, pintura, laca o barnices)', valor_excel: '' },
        { id: 'UFIC-073', numero: 73, norma: 'R.6.3', pregunta: 'El conductor de tierra de protección es de color verde o desnudo de Cu', valor_excel: '' },
        { id: 'UFIC-074', numero: 74, norma: 'N.250-92.a', pregunta: 'No se usan como conductores de puesta a tierra conductores aislados o desnudos de Al o recubierto de cobre que estén en contacto directo con las paredes de mampostería o con tierra o si están sometidos a condiciones corrosivas. Cuando se utilicen en el exterior, no se instalaron a menos de 0,5 m del suelo.', valor_excel: '' },
        { id: 'UFIC-075', numero: 75, norma: 'N. 250-94', pregunta: 'El calibre del conductor del electrodo de puesta a tierra no es inferior al estipulado en la tabla 250-94 NTC 2050', valor_excel: '' },
        { id: 'UFIC-076', numero: 76, norma: 'N.250-23.b', pregunta: 'Cuando los conductores de fase de acometida se conecten en paralelo, el calibre del conductor puesto a tierra se selecciona sobre la base de una sección equivalente para conductores en paralelo.', valor_excel: '' },
        { id: 'UFIC-077', numero: 77, norma: 'N.250-86', pregunta: 'El calibre del conductor del electrodo de puesta a tierra para corriente continua CC cumple las siguientes condiciones: -a) No es de calibre menor al del neutro -b) No es de calibre menor al del conductor más grande. -c) No es de calibre menor a (8 AWG).', valor_excel: '' },
        { id: 'UFIC-078', numero: 78, norma: 'R. 15.1.', pregunta: 'Las conexiones que van bajo el nivel del suelo (SPT), se realizan con soldadura exotérmica o conector certificado para enterramiento directo.', valor_excel: '' },
        { id: 'UFIC-079', numero: 79, norma: 'N.250-115', pregunta: 'Al electrodo de puesta a tierra no se le conecta más de un conductor con la misma abrazadera o herraje, excepto si la abrazadera o herraje están certificados para usarlos con varios conductores.', valor_excel: '' },
        { id: 'UFIC-080', numero: 80, norma: 'R. 15.3.1.f', pregunta: 'El electrodo tipo varilla o tubo tiene mínimo 2,4 m', valor_excel: '' },
        { id: 'UFIC-081', numero: 81, norma: 'R. 15.3.1.b', pregunta: 'No se permite el uso de aluminio en los electrodos de las puestas a tierra.', valor_excel: '' },
        { id: 'UFIC-082', numero: 82, norma: 'R. 15.1.', pregunta: 'Si existen varias puestas a tierra (Protección contra rayos, protección catódica, etc.),  estan interconectadas eléctricamente', valor_excel: '' },
        { id: 'UFIC-083', numero: 83, norma: 'N.250-86', pregunta: 'Para la puesta a tierra de los sistemas eléctricos y equipos no se usa la puesta a tierra de pararrayos.', valor_excel: '' },
        { id: 'UFIC-084', numero: 84, norma: 'N.250-83.a', pregunta: 'No se usa como electrodo de puesta a tierra la instalación subterránea de tuberías metálicas de gas', valor_excel: '' },
        { id: 'UFIC-085', numero: 85, norma: 'R. 15.', pregunta: 'Los apoyos o estructuras metálicas se encuentran puestas a tierra.', valor_excel: '' },
        { id: 'UFIC-086', numero: 86, norma: 'N.250-32  N.250-33', pregunta: 'Se colocaron a tierra los armarios, cerramientos y canalizaciones metálicos de los conductores de la acometida y alimentadores', valor_excel: '' },
      ],
    },
    {
      id: '5__Tablero_de_distribuci_n',
      titulo: '5. Tablero de distribución',
      preguntas: [
        { id: 'UFIC-087', numero: 87, norma: 'R.27.4.3.d', pregunta: 'El Tablero de Distribucion es fácilmente accesible', valor_excel: '' },
        { id: 'UFIC-088', numero: 88, norma: 'R. 20.23.4 o.', pregunta: 'Los tableros eléctricos y los conductores de control y de potencia se encuentran plenamente identificados', valor_excel: '' },
        { id: 'UFIC-089', numero: 89, norma: 'R. 20.23.4 n.', pregunta: 'Los cables de control están alambrados en canaleta.', valor_excel: '' },
        { id: 'UFIC-090', numero: 90, norma: 'N.110-16. a.2', pregunta: 'Las puertas del tablero abren 90° como mínimo', valor_excel: '' },
        { id: 'UFIC-091', numero: 91, norma: 'R. 10.4. N. 110-16. a', pregunta: 'Se cumple con las distancias mínimas permitidas para el espacio de trabajo. (600 V o menos)', valor_excel: '' },
        { id: 'UFIC-092', numero: 92, norma: 'N. 110-34. a', pregunta: 'El espacio de trabajo alrededor del equipo eléctrico (más de 600 V) se cumple, según Artículo 110-34', valor_excel: '' },
        { id: 'UFIC-093', numero: 93, norma: 'R. 10.4', pregunta: 'El cuarto eléctrico cuenta con puertas o espacios adecuados para la entrada o salida de equipos. El ancho del ala de la puerta no es menor a 90 cm.', valor_excel: '' },
        { id: 'UFIC-094', numero: 94, norma: 'R. 20.23.1.4.f', pregunta: 'El tablero tiene logo de riesgo eléctrico e identificación.', valor_excel: '' },
        { id: 'UFIC-095', numero: 95, norma: 'N. 110-16. d', pregunta: 'Existe iluminación en todos los espacios de trabajo alrededor de los equipos de acometida, tableros de distribución o centros de control de motores. No es necesario elementos adicionales si la iluminación proviene de fuente adyacente(600 V o menos)', valor_excel: '' },
        { id: 'UFIC-096', numero: 96, norma: 'N. 110-16. d', pregunta: 'En los cuartos de equipos eléctricos, la iluminación no es accionada exclusivamente por medios automáticos(600 V o menos)', valor_excel: '' },
        { id: 'UFIC-097', numero: 97, norma: 'N.384-4. a) 1) N.110-16 .f) 1)', pregunta: 'En paneles de distribucion y centros de control de motores ubicados en interiores se cumple espacio dedicado,en esta zona no se debe ubicar tuberia, ductos o equipos ajenos, se permiten rociadores. Para la instalacion se dispone de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta una altura de 7.6 m o hasta el techo,', valor_excel: '' },
        { id: 'UFIC-098', numero: 98, norma: 'N. 110-34. d', pregunta: 'Hay iluminación con una intensidad mínima de 100 luxes alrededor de los equipos eléctricos (más de 600 V)', valor_excel: '' },
        { id: 'UFIC-099', numero: 99, norma: 'N. 110-34. d', pregunta: 'Las salidas para alumbrado estan dispuestas de manera que las personas que cambien las bombillas o hagan reparaciones en el sistema de alumbrado, no corran peligro por las partes u otros equipos energizados.  (más de 600 V)', valor_excel: '' },
        { id: 'UFIC-100', numero: 100, norma: 'N. 110-34. d', pregunta: 'Los puntos de mando están situados de modo que no sea probable que las personas entren en contacto con ninguna parte energizada o móvil del equipo cuando  encienden el alumbrado(más de 600 V)', valor_excel: '' },
        { id: 'UFIC-101', numero: 101, norma: 'R. 6.3', pregunta: 'En sistemas con tensión superior a 380 V, adicional a los colores, se indicó en los tableros y en puntos accesibles de conductores, una leyenda con el aviso del nivel de tensión respectivo.', valor_excel: '' },
        { id: 'UFIC-102', numero: 102, norma: 'R.20.23.1.4.a-e', pregunta: 'El tablero tiene adherida de manera clara, permanente y visible placa con características técnicas.', valor_excel: '' },
        { id: 'UFIC-103', numero: 103, norma: 'R. 20.23.1.4.g,i', pregunta: 'El tablero tiene cuadro para identificar circuitos y diagrama unifilar actualizado.', valor_excel: '' },
        { id: 'UFIC-104', numero: 104, norma: 'R. 20.5.2. f', pregunta: 'Las aberturas no utilizadas están cerradas eficazmente', valor_excel: '' },
        { id: 'UFIC-105', numero: 105, norma: 'N. 373-8', pregunta: 'NO existen empalmes dentro del tablero.', valor_excel: '' },
        { id: 'UFIC-106', numero: 106, norma: 'R.20.23.4.g', pregunta: 'Los cables no atraviesan barrajes', valor_excel: '' },
        { id: 'UFIC-107', numero: 107, norma: 'R. 20.23.1.3.f', pregunta: 'Se cumple el código de colores.', valor_excel: '' },
        { id: 'UFIC-108', numero: 108, norma: 'N.384-3. f) R. 20.23.1.2.d', pregunta: 'Cableado-barrajes cumplen disposición de las fases; A, B, C, de frente a posterior; superior a inferior, o de izquierda a derecha, vista desde el frente del tablero.', valor_excel: '' },
        { id: 'UFIC-109', numero: 109, norma: 'R.6.3', pregunta: 'Ningún circuito utiliza el blanco ni el verde para las fases.', valor_excel: '' },
        { id: 'UFIC-110', numero: 110, norma: 'N. 250-95', pregunta: 'Cuando haya conductores en paralelo (sólo para mayores a calibres 1/0 AWG de Cu o Al) en varios conductos o cables, como lo permite el Artículo 310-4, el conductor de puesta a tierra de equipos, cuando exista está instalado en paralelo.', valor_excel: '' },
        { id: 'UFIC-111', numero: 111, norma: 'R.20.2.9.j', pregunta: 'Cables o alambres de Aluminio o Alumino recubierto en cobre se cumple lo siguiente: 1. Son de la serie AA 8000.-2. Empleo de conectores bimetálicos - 3. Ser instalados y mantenidos por personas calificadas, con la competencia profesional certificada. -4. A toda conexión se le aplica gel retardantes de la oxidación. -5. Sobre el cuerpo del dispositivo o equipo para uso directo con conductores de aluminio, se fija rotulado de advertencia en fondo de color amarillo y letra negra.', valor_excel: '' },
        { id: 'UFIC-112', numero: 112, norma: 'R. 27.4.3. c.', pregunta: 'La capacidad de corriente del conductor de cada circuito ramal es superior a la capacidad de corriente de la protección asociada. Ver tabla 310-16 NTC 2050.', valor_excel: '' },
        { id: 'UFIC-113', numero: 113, norma: 'R. 20.23.4.j', pregunta: 'Se utilizan terminales para conexión entre cables y barrajes.', valor_excel: '' },
        { id: 'UFIC-114', numero: 114, norma: 'R. 20.23.4.c', pregunta: 'En los tableros con sistema de instalación tipo Riel DIN no se supera el nivel de ocupación definido por el productor', valor_excel: '' },
        { id: 'UFIC-115', numero: 115, norma: 'R.20.16.2.2.e', pregunta: 'Cada circuito ramal presenta protección contra sobrecorriente.', valor_excel: '' },
        { id: 'UFIC-116', numero: 116, norma: 'R.27.4.1.e', pregunta: 'Cada circuito dispone de dispositivo de corte automático de la alimentación.', valor_excel: '' },
        { id: 'UFIC-117', numero: 117, norma: 'R.20.16.2.2.a', pregunta: 'En los interruptores automáticos el circuito alimentador llegue al terminal línea y la salida se conecte a los terminales carga.', valor_excel: '' },
        { id: 'UFIC-118', numero: 118, norma: 'R.20.16.2.2.b', pregunta: 'Los interruptores automáticos tienen unas especificaciones de corriente y tensión, no menores a los valores nominales de los circuitos que controlan.', valor_excel: '' },
        { id: 'UFIC-119', numero: 119, norma: 'R. 20.23.1.3. c.', pregunta: 'El tablero cuenta con barrajes de tierra y neutro, con suficientes terminales de salida.', valor_excel: '' },
        { id: 'UFIC-120', numero: 120, norma: 'R.20.12.2.a', pregunta: 'No se instala dos o más conectores o terminales en la misma bornera o al mismo tornillo.', valor_excel: '' },
        { id: 'UFIC-121', numero: 121, norma: 'R.20.23.1.2.e', pregunta: 'El tablero se encuentra sólidamente puesto a tierra.', valor_excel: '' },
        { id: 'UFIC-122', numero: 122, norma: 'R. 15.3.3.d.', pregunta: 'El conductor de puesta a tierra de equipos acompaña los conductores activos durante todo su recorrido y por la misma canalización.', valor_excel: '' },
        { id: 'UFIC-123', numero: 123, norma: 'R.15.3.3.c', pregunta: 'El Conductor de puesta a tierra de equipos es continuo, sin interruptores o medios de desconexión y cuando se empalmen (es mecánica y eléctricamente seguro con soldadura o conector certificados para tal uso)', valor_excel: '' },
        { id: 'UFIC-124', numero: 124, norma: 'R.15.3.3.e', pregunta: 'El Conductor de puesta a tierra de equipos que por disposición de la instalación se requieran aislar, son de color verde, verde con rayas amarillas o identificados con marcas verdes en los puntos de inspección y extremos', valor_excel: '' },
        { id: 'UFIC-125', numero: 125, norma: 'N. 250-95', pregunta: 'El conductor de tierra de cada circuito ramal cumple el calibre mínimo dado en la tabla 250-95 NTC 2050.', valor_excel: '' },
        { id: 'UFIC-126', numero: 126, norma: 'N.280-21', pregunta: 'Circuito de menos de 1000 V los conductores de conexión DPS a la red y a tierra no son de calibre menor a 14 AWG en Cu o 12 AWG en Al.', valor_excel: '' },
        { id: 'UFIC-127', numero: 127, norma: 'N.280-4.a', pregunta: 'Circuito de menos de 1000 V el valor nominal del descargador de sobretensiones es = o mayor que la máxima tensión continua de fase a tierra', valor_excel: '' },
        { id: 'UFIC-128', numero: 128, norma: 'R.20.23.4.o', pregunta: 'Realizar las pruebas de aislamiento: Las mediciones deben ser realizadas usando un megómetro a una tensión de por lo menos 500 Vcc. El valor de la resistencia de aislamiento debe ser no menor de 1000 Ω/V.', valor_excel: '' },
      ],
    },
    {
      id: '6__Circuitos_Ramales',
      titulo: '6. Circuitos Ramales',
      preguntas: [
        { id: 'UFIC-129', numero: 129, norma: 'R. 20.10.2. f.', pregunta: 'El tomacorriente instalado de forma horizontal, el contacto superior corresponde la neutro.', valor_excel: '' },
        { id: 'UFIC-130', numero: 130, norma: 'N. 210-21. b.1', pregunta: 'Un tomacorriente instalado en un circuito ramal individual tiene capacidad de corriente no menor a la de dicho circuito.', valor_excel: '' },
        { id: 'UFIC-131', numero: 131, norma: 'R. 20.5.2.e', pregunta: 'En las cajas para alojar equipos NO se retiraron las tapas de entrada de ductos no utilizadas, ni se hicieron perforaciones adicionales.', valor_excel: '' },
        { id: 'UFIC-132', numero: 132, norma: 'N. 210-8. b', pregunta: 'En edificaciones que no sean viviendas, existe toma GFCI instalada en los siguientes lugares: 1) Cuartos de baños. 2) Azoteas', valor_excel: '' },
        { id: 'UFIC-133', numero: 133, norma: 'R. 20.10.2 c.', pregunta: 'Los tomacorrientes instalados en lugares sujetos a la lluvia o salpicadura de agua tienen una cubierta protectora.', valor_excel: '' },
        { id: 'UFIC-134', numero: 134, norma: 'R.20.5.2.c', pregunta: 'Las cajas están instaladas de modo que su borde frontal no se encuentra a más de 15 mm de la superficie de acabado final.', valor_excel: '' },
        { id: 'UFIC-135', numero: 135, norma: 'N.300-14', pregunta: 'En las salidas, uniones y de interruptores, queda como mínimo una longitud de 15 cm libre en los conductores.', valor_excel: '' },
        { id: 'UFIC-136', numero: 136, norma: 'N.250-114', pregunta: 'El empalme de diferentes conductores de puesta a tierra se hace dentro de la caja que los contiene y no en el aparato o equipo respectivo.', valor_excel: '' },
        { id: 'UFIC-137', numero: 137, norma: 'N.250-114.a', pregunta: 'Todas las cajas metálicas que contengan aparatos están puestas a tierra por tornillo que no se dio ningún otro uso', valor_excel: '' },
        { id: 'UFIC-138', numero: 138, norma: 'N.250-114.b', pregunta: 'Toda caja NO metálica que contenga aparatos se le instaló el respectivo conductor de puesta a tierra', valor_excel: '' },
        { id: 'UFIC-139', numero: 139, norma: 'R.15.3.3.c', pregunta: 'Los conductores del sistema de puesta a tierra de equipos son continuos sin interruptores y sus empalmes son mecánica y eléctricamente seguros mediante soldadura o conectores certificados', valor_excel: '' },
        { id: 'UFIC-140', numero: 140, norma: 'R. 27.4.2.c.', pregunta: 'Todas las carcasas o masas de equipos y cajas para alojar equipos (cajas de paso, tomacorrientes, rosetas, canaletas, etc.) tienen conexión a tierra (MEDIDA EQUIPOTENCIAL)', valor_excel: '' },
        { id: 'UFIC-141', numero: 141, norma: 'R. 20.5.2.a R.20. k.', pregunta: 'Productos como: Las barras colectoras, terminales de cables, aisladores, interruptores, cajas para alojar equipos entre otros, no están dañados o contaminados por pintura, yeso, concreto, abrasivos o corrosivos', valor_excel: '' },
        { id: 'UFIC-142', numero: 142, norma: 'R.6.3', pregunta: 'No se utiliza el blanco ni el verde para las fases.', valor_excel: '' },
        { id: 'UFIC-143', numero: 143, norma: 'R.20.10.2.a', pregunta: 'La conexión de los conductores eléctricos a los terminales de los tomacorrientes y clavijas es lo suficientemente segura para evitar recalentamientos de los contactos.', valor_excel: '' },
        { id: 'UFIC-144', numero: 144, norma: 'R.20.16.3.2.e', pregunta: 'Los interruptores están provistos de sus respectivas tapas que impiden el contacto con partes energizadas.', valor_excel: '' },
        { id: 'UFIC-145', numero: 145, norma: 'R. 20.6.1.2. h.', pregunta: 'NO se instalan tuberías no metálicas livianas (Tipo A), expuestas ni en cielos falsos.', valor_excel: '' },
        { id: 'UFIC-146', numero: 146, norma: 'R.20.5.2.d', pregunta: 'En paredes o cielorrasos construidos en madera u otro material combustible, las cajas se instalaron a ras o sobresalen de la superficie de acabado', valor_excel: '' },
        { id: 'UFIC-147', numero: 147, norma: 'R.28.1.c.', pregunta: 'Existe tomacorrientes con protección de falla a tierra en todos los espacios en condiciones de mayor vulnerabilidad como  casos de piel mojada o sumergida ( zona de lavado)', valor_excel: '' },
        { id: 'UFIC-148', numero: 148, norma: 'R. 20.6.a.', pregunta: 'Las canalizaciones expuestas o a la vista, están marcadas con franjas de color naranja de mínimo 10 cm', valor_excel: '' },
        { id: 'UFIC-149', numero: 149, norma: 'R.20.6.b', pregunta: 'Si en una misma canalización se instalan conductores eléctricos con cableados o tuberías para otros usos, existe una separación física entre ellos', valor_excel: '' },
        { id: 'UFIC-150', numero: 150, norma: 'N.348-12', pregunta: 'Las tuberías metalica EMT se deben apoyar como mínimo cada 3,0 m. Además el tubo se debe sujetar bien a menos de 0,9 m de cada caja de salida, caja de corte, caja de dispositivos, armario, conduleta u otra terminación cualquiera.', valor_excel: '' },
        { id: 'UFIC-151', numero: 151, norma: 'N.348-1', pregunta: 'No se empleo tubería EMT en áreas con condiciones de corrosión (zonas húmedas, gases, vapores, etc.)', valor_excel: '' },
        { id: 'UFIC-152', numero: 152, norma: 'R.20.6.1 .1.b', pregunta: 'La tubería y sus accesorios no presentan elementos cortantes', valor_excel: '' },
        { id: 'UFIC-153', numero: 153, norma: 'R.20.6.1 .2.a', pregunta: 'La tubería instalada en ambientes corrosivos, con humedad permanente o bajo tierra esta certificada para ese uso', valor_excel: '' },
        { id: 'UFIC-154', numero: 154, norma: 'R.20.6.1 .2.b', pregunta: 'En edificaciones de más de tres pisos, las tuberías eléctricas plegables no metálicas están ocultas dentro de cielorrasos, cielos falsos, pisos, muros o techos, siempre y cuando los materiales constructivos usados tengan una resistencia al fuego de mínimo 15 minutos, o menos si se tiene un sistema contra incendio de regaderas automáticas en toda la edificación.', valor_excel: '' },
        { id: 'UFIC-155', numero: 155, norma: 'R.20.6.1.2.c', pregunta: 'La distancia entre accesorios que soportan la tubería no metalica no es mayor a:-a) 1,2 m para tubería hasta de 19 mm de diámetro- b) 1,5 m para tuberías entre 25 y 51 mm-c) 1,8 m para tuberías entre 63 y 76 mm-d) 2,1 m para tuberías entre 89 y 102 mm', valor_excel: '' },
        { id: 'UFIC-156', numero: 156, norma: 'R.20.6.1.2.e', pregunta: 'No se permite el uso de tubería eléctrica plegable no metálica, como soporte de aparatos, enterrada directamente en el suelo, ni para tensiones mayores de 600 V, a no ser que esté certificada para su uso', valor_excel: '' },
        { id: 'UFIC-157', numero: 157, norma: 'N.210-63', pregunta: 'Existe una tomacorriente monofásica de 125 V y 15 A o 20 A para el mantenimiento de los equipos de calefacción, congeladores y aire acondicionado en azoteas, aticos y espacios bajo el suelo', valor_excel: '' },
        { id: 'UFIC-158', numero: 158, norma: 'N.210-70.c', pregunta: 'Existe una salida de alumbrado controlada por un interruptor de pared, cerca de los equipos que requieran revisión, como los de calefacción, refrigeración o aire acondicionado. El interruptor se instaló en el punto de entrada al ático o al espacio bajo el piso', valor_excel: '' },
      ],
    },
    {
      id: '7__Ba_os',
      titulo: '7. Baños',
      preguntas: [
        { id: 'UFIC-159', numero: 159, norma: 'N. 210-70. a', pregunta: 'En el cuarto del baño existe una salida para alumbrado con interruptor de pared.', valor_excel: '' },
        { id: 'UFIC-160', numero: 160, norma: 'R. 28.1. g. 4.', pregunta: 'Las instalaciones localizadas en alturas por encima de 1500 msnm, tienen 1 circuito exclusivo para ducha eléctrica, a menos que se disponga de otro medio para el calentamiento del agua.', valor_excel: '' },
        { id: 'UFIC-161', numero: 161, norma: 'R. 28.1. e. R.20.15.2. b', pregunta: 'Las ducha eléctrica, esta instalado en circuito de capacidad no menor a 30 A para instalación monofásica a tensión menor de 150 V y 20 A para 208/220/240 V protegidos con un interruptor automático, con neutro y conductor de tierra plenamente identificados y conectado sólidamente a tierra o disponer de una protección diferencial.', valor_excel: '' },
        { id: 'UFIC-162', numero: 162, norma: 'R. 20.15.2 d.', pregunta: 'La ducha eléctrica se encuentra puesta a tierra', valor_excel: '' },
        { id: 'UFIC-163', numero: 163, norma: 'R.20.15.2. e.', pregunta: 'En el cuarto de baño la ducha no tiene partes localizadas a menos de 2 m del piso.', valor_excel: '' },
        { id: 'UFIC-164', numero: 164, norma: 'N.210-52.d', pregunta: 'En los cuartos de baño, se instaló por lo menos un tomacorriente en la pared adyacente a cada lavamanos y esta alimentado por circuito ramal de minimo 20 A.', valor_excel: '' },
        { id: 'UFIC-165', numero: 165, norma: 'R.28.1.d', pregunta: 'Las tomacorrientes son GFCI y los interruptores no estan instalados a menos de 80 cm de la puerta de la zona de la ducha', valor_excel: '' },
      ],
    },
    {
      id: '8__Iluminaci_n_',
      titulo: '8. Iluminación.',
      preguntas: [
        { id: 'UFIC-166', numero: 166, norma: 'R. 20.29.2. a', pregunta: 'En los portalámparas la fase esta conectada en el terminal central y el neutro a la camisa roscada.', valor_excel: '' },
        { id: 'UFIC-167', numero: 167, norma: 'R. 20.29.2. b', pregunta: 'Se asegura la evacuación de calor producida por la lámpara.', valor_excel: '' },
        { id: 'UFIC-168', numero: 168, norma: 'R.17.1.c', pregunta: 'Se verifica funcionamiento de las luminarias de emergencia por un periodo minimo de 60 minutos despues de que se interrumpa el servicio electrico normal', valor_excel: '' },
        { id: 'UFIC-169', numero: 169, norma: 'R. 20.5.2. b.', pregunta: 'Las cajas para salidas de alumbrado NO son rectangulares.', valor_excel: '' },
        { id: 'UFIC-170', numero: 170, norma: 'R. 20.16.3.1 a.', pregunta: 'Las posiciones de encendido y apagado están claramente indicadas en el cuerpo del interruptor. Este requisito es exigible para uso final industrial', valor_excel: '' },
        { id: 'UFIC-171', numero: 171, norma: 'R. 20.16.3.1 c.', pregunta: 'Las cubiertas o tapas metálicas se protegen mediante aislamiento adicional hecho por revestimientos o barreras aislantes', valor_excel: '' },
        { id: 'UFIC-172', numero: 172, norma: 'R. 20.16.3.1 d.', pregunta: 'Para uso a la intemperie, los interruptores están protegidos mediante encerramiento a prueba de lluvia.', valor_excel: '' },
        { id: 'UFIC-173', numero: 173, norma: 'R. 20.16.3.1 Parágrafo 1', pregunta: 'Los reguladores de corriente o tensión conocidos como Dimers y utilizados como interruptores manuales para usos domiciliarios o similares, cumplen los requisitos para interruptores y demostrarlo mediante Certificado de Conformidad de Producto.', valor_excel: '' },
        { id: 'UFIC-174', numero: 174, norma: 'R. 20.16.3.1 Parágrafo 3', pregunta: 'Sobre el cuerpo del interruptor para uso directo con conductores de aluminio, se fijó un rotulado de advertencia en fondo de color amarillo y letra negra, en el cual se informe al usuario que el reemplazo de dicho dispositivo se realizará con uno apto para conexión de aluminio', valor_excel: '' },
        { id: 'UFIC-175', numero: 175, norma: 'R. 20.16.3.1 Parágrafo 2', pregunta: 'Los interruptores manuales de baja tensión denominados cuchillas, cumplen los requisitos de seguridad de una norma internacional, de reconocimiento internacional o NTC que les aplique y lo demuestran mediante Certificado de Conformidad de Producto. El uso de este tipo de interruptores (cuchillas) estará ceñido a las restricciones dadas en la norma que les aplique.', valor_excel: '' },
      ],
    },
    {
      id: '9__Producto',
      titulo: '9. Producto',
      preguntas: [
        { id: 'UFIC-176', numero: 176, norma: 'R.20. i.', pregunta: 'Todo producto esta rotulado con: la marca comercial, el nombre o logotipo del productor.', valor_excel: '' },
        { id: 'UFIC-177', numero: 177, norma: 'R.20.2.9.d.', pregunta: 'En los conductores instalados, se cumple con el radio mínimo de curvatura que recomienda el productor.', valor_excel: '' },
        { id: 'UFIC-178', numero: 178, norma: 'R.20.6.1.2.f.', pregunta: 'No hay tuberías no metálicas instaladas en lugares expuestos a daños físicos o a la luz solar directa.', valor_excel: '' },
        { id: 'UFIC-179', numero: 179, norma: 'R.20.9.2.', pregunta: 'Las cintas aislantes usadas en instalaciones eléctricas exteriores son de color negro.', valor_excel: '' },
        { id: 'UFIC-180', numero: 180, norma: 'R.20.10.2.d', pregunta: 'En ambientes con chorros de agua (lugares de lavado) se emplearon enchufes y tomacorrientes con encerramiento no menor a IP67 o su equivalente NEMA. Los tomacorrientes GFCI no son aptas para estas aplicaciones, a menos que el productor así lo garantice.', valor_excel: '' },
        { id: 'UFIC-181', numero: 181, norma: 'R.20.23.4. q', pregunta: 'No hay tableros instalados en paredes contiguas a los peldaños de las escaleras.', valor_excel: '' },
        { id: 'UFIC-182', numero: 182, norma: 'R. 20.2.9 e.', pregunta: 'En interiores o en espacios donde se tenga la presencia de materiales inflamables, no se instalaron conductores que permitan propiciar la llama o facilitar su propagación.', valor_excel: '' },
        { id: 'UFIC-183', numero: 183, norma: 'R. 20.16.5', pregunta: 'Para diferenciar los botones, se emplea el verde esmeralda para el botón de arranque y el rojo para todos los dispositivos de parada', valor_excel: '' },
      ],
    },
    {
      id: '10__Bandejas_portacables',
      titulo: '10. Bandejas portacables',
      preguntas: [
        { id: 'UFIC-184', numero: 184, norma: 'R. 20.3 c.', pregunta: 'Las bandejas no presentan elementos cortantes', valor_excel: '' },
        { id: 'UFIC-185', numero: 185, norma: 'R. 20.3 d.', pregunta: 'La bandeja no metálica es de material retardarte a la llama, no propagador de incendios y de baja emisión de gases tóxicos', valor_excel: '' },
        { id: 'UFIC-186', numero: 186, norma: 'R. 20.3 e', pregunta: 'En la bandeja no van instalados junto a los conductores eléctricos tuberías para otros usos.', valor_excel: '' },
        { id: 'UFIC-187', numero: 187, norma: 'R. 20.3 f.', pregunta: 'Los cables expuestos a radiación ultravioleta instalados en bandeja son resistentes a este tipo de radiación', valor_excel: '' },
        { id: 'UFIC-188', numero: 188, norma: 'R. 20.3 g', pregunta: 'Se asegura la equipotencialidad entre las diferentes secciones de la bandeja portacable', valor_excel: '' },
        { id: 'UFIC-189', numero: 189, norma: 'R. 20.3 i', pregunta: 'Los conductores instalados sobre bandejas están certificados y rotulados para este uso.', valor_excel: '' },
        { id: 'UFIC-190', numero: 190, norma: 'R. 20.3 i', pregunta: 'No superan el 40% del volumen de llenado de la bandeja para cables de potencia.', valor_excel: '' },
        { id: 'UFIC-191', numero: 191, norma: 'R. 20.3 i', pregunta: 'Los conductores se marcaron en partes visibles dando cumplimiento al código de colores.', valor_excel: '' },
        { id: 'UFIC-192', numero: 192, norma: 'R. 20.3 j', pregunta: 'Para Bandejas, los cables de sección mayor a 12 AWG están separados de los de sección mayor a 1/0 AWG por una pared rígida de material compatible con el de la bandeja', valor_excel: '' },
        { id: 'UFIC-193', numero: 193, norma: 'N. 318-6.h', pregunta: 'Las bandejas son expuestas y accesibles, y hay espacio suficiente para la instalación y mantenimiento del cableado', valor_excel: '' },
        { id: 'UFIC-194', numero: 194, norma: 'N. 318-6.f', pregunta: 'No están instalados en bandeja cables de mas de 600V con cables menos de 600V', valor_excel: '' },
        { id: 'UFIC-195', numero: 195, norma: 'R. 20.3.K', pregunta: 'En instalaciones especiales se puede aceptar la bandeja metálica si es certificada resistente al fuego a 1000 ºC (90 min) y los conductores instalados son a prueba de fuego.', valor_excel: '' },
        { id: 'UFIC-196', numero: 196, norma: 'N.318.4', pregunta: 'Las bandejas Portacables no están instaladas en huecos de los ascensores o donde puedan estar sujetos a daños físicos y no están instaladas en espacios de circulación de aire de ventilación', valor_excel: '' },
        { id: 'UFIC-197', numero: 197, norma: 'N. 318-6.a', pregunta: 'Se permite que haya en una bandeja portacables empalmes hechos y aislados con métodos aprobados, siempre que sean accesibles y no sobresalgan de las barandillas laterales.', valor_excel: '' },
        { id: 'UFIC-198', numero: 198, norma: 'N. 318-8.b', pregunta: 'En los tramos distintos a los horizontales, los cables están sujetos firmemente a los travesaños de las bandejas.', valor_excel: '' },
        { id: 'UFIC-199', numero: 199, norma: 'N. 318-8.d', pregunta: 'Conectados en paralelo. Cuando los cables de un solo conductor (fase o neutro) de un circuito se conecten en paralelo como lo permite el Artículo 310-4, los conductores se deben instalar en grupos, consistentes en no más de un conductor de fase o neutro para evitar desequilibrios de corriente en conductores debidos a la reactancia inductiva. conductores sencillos se deben empaquetar firmemente en grupos evitando movimient excesivo si se producen fuerzas magnéticas por fallas a tierra.', valor_excel: '' },
        { id: 'UFIC-200', numero: 200, norma: 'N. 318-8.e', pregunta: 'Los conductores sencillos(1/0 AWG a 4/0 AWG) instalados en la bandeja portacables escalera o canal ventilado se instalados en una misma capa.', valor_excel: '' },
      ],
    },
    {
      id: '11__Canaleta',
      titulo: '11. Canaleta',
      preguntas: [
        { id: 'UFIC-201', numero: 201, norma: 'R. 20.6.2.2.a', pregunta: 'No se permite el uso de canaletas no metálicas en: Instalaciones ocultas (excepto cuando atraviesan muros o paredes), donde estén expuestas a daño físico, en los espacios vacíos de ascensores, en ambientes con temperaturas superiores a las certificadas.', valor_excel: '' },
        { id: 'UFIC-202', numero: 202, norma: 'R.20.6.2.2. b', pregunta: 'Las canaletas están instaladas de tal manera que se asegura la continuidad mecánica y la continuidad eléctrica por medio de puentes equipotenciales.', valor_excel: '' },
        { id: 'UFIC-203', numero: 203, norma: 'R.20.6.2.2.c.', pregunta: 'Deben estar sólidamente montadas y con encerramiento completo.', valor_excel: '' },
        { id: 'UFIC-204', numero: 204, norma: 'R.20.6.2.2. d.', pregunta: 'Se debe evitar la abrasión o el corte del aislamiento de los conductores, mediante el uso de pasacables, tubos o accesorios adecuados.', valor_excel: '' },
        { id: 'UFIC-205', numero: 205, norma: 'R. 20.6.3.2 a.', pregunta: 'En instalaciones verticales en donde la canalización con barras incorporadas pasa a través de varios pisos, en cada uno de ellos se instaló un muro de mínimo 11 cm de altura alrededor de la canalización y distanciado del borde del orificio al menos 30 cm, con el fin de proteger la canalización de derrames de líquidos.', valor_excel: '' },
        { id: 'UFIC-206', numero: 206, norma: 'R. 20.6.3.2 b.', pregunta: 'Cuando se instale el electroducto de forma vertical en instalaciones comerciales tiene un IP no menor a 44.', valor_excel: '' },
        { id: 'UFIC-207', numero: 207, norma: 'R. 20.6.3.2 c.', pregunta: 'Los puntos de soporte están instalados a no más de 1,5 m, a no ser que la placa especifique otra cosa', valor_excel: '' },
        { id: 'UFIC-208', numero: 208, norma: 'R. 20.6.3.2 d.', pregunta: 'En la perforación entre pisos se dejan espacios (mantenimiento) de tal forma que a los lados y parte trasera se separe 20 cm de la barra y 30 cm de frente', valor_excel: '' },
      ],
    },
    {
      id: '13__Requisitos_generales',
      titulo: '13. Requisitos generales',
      preguntas: [
        { id: 'UFIC-209', numero: 209, norma: 'N.110-12', pregunta: 'Los equipos eléctricos se instalaron de manera limpia y profesional.', valor_excel: '' },
        { id: 'UFIC-210', numero: 210, norma: 'N. 110-13 .a', pregunta: 'Los equipos eléctricos se instalaron firmemente a la superficie', valor_excel: '' },
        { id: 'UFIC-211', numero: 211, norma: 'N.110-3.b', pregunta: 'Los productos eléctricos fueron instalados para fines exclusivos para los que fueron certificados', valor_excel: '' },
        { id: 'UFIC-212', numero: 212, norma: 'N.300-4', pregunta: 'Los conductores eléctricos (acometida, alimentador o circuitos ramales) se encuentran debidamente protegidos contra daños físicos', valor_excel: '' },
        { id: 'UFIC-213', numero: 213, norma: 'R.20.23.4.o', pregunta: 'Se realizan las siguientes verificaciones: 1. Funcionalidad de las rejillas de ventilación, las tapas laterales y las puertas. 2. Identificaciones del tablero y de los conductores de control y potencia. 3. Conexión a tierra de las puertas. 4. Remover el polvo. 5. Medir equipotencialidad entre partes conductoras del tablero. 6. Verificar los torques de las uniones mecánicas, eléctricas y de anclaje. 7. Verificar  los enclavamientos mecánicos de los equipos del tablero. 8. Inspeccionar visualmente de toda la estructura del tablero, especialmente la pintura. 9.Remover todos los objetos extraños (restos de cables, tuercas, tornillos, herramientas, etc.).', valor_excel: '' },
      ],
    },
    {
      id: '14__Motores',
      titulo: '14. Motores',
      preguntas: [
        { id: 'UFIC-214', numero: 214, norma: 'R. 20.21.1.b', pregunta: 'Si es generador, cuenta con protección contra sobrevelocidad y protección contra sobrecorriente.', valor_excel: '' },
        { id: 'UFIC-215', numero: 215, norma: 'R. 20.21.1.c', pregunta: 'Todo motor o generador eléctrico está provisto de un diagrama de conexiones, el cual está adherido al encerramiento y una o varias placas de características. Las placas se elaboraron en un material durable, con letras indelebles e instalan en un sitio visible y de manera que no sean removibles, contienen la siguiente minimo:-Razón social o marca registrada del productor, comercializador o importador.-Tensión nominal o intervalo de tensiones nominales.-Corriente nominal.- Potencia nominal, hasta 1000 msnm. Frecuencia nominal o especificar que es corriente continua.-Velocidad nominal o intervalo de velocidades nominales.-Número de fases para máquinas de corriente alterna.-Grados de protección IP.-Eficiencia energética a condiciones nominales de operación.- Para las máquinas corriente alterna factor de potencia nominal.', valor_excel: '' },
        { id: 'UFIC-216', numero: 216, norma: 'R.20.21.1 Parágrafo 2', pregunta: 'Si una persona distinta del productor repara o modifica parcial o totalmente el devanado de una máquina o cualquier otro de sus componentes, se instaló una placa adicional para indicar el nombre del reparador, el año de reparación y las modificaciones efectuadas', valor_excel: '' },
        { id: 'UFIC-217', numero: 217, norma: 'R.20.21.2.a.c', pregunta: 'Se atendió las indicaciones y recomendaciones de montaje (incluyendo posición vertical o horizontal) del fabricante', valor_excel: '' },
        { id: 'UFIC-218', numero: 218, norma: 'R.20.21.2.d', pregunta: 'Las carcasas están sólidamente conectadas a tierra. Los generadores tienen un sistema aislado de tierra, es cual es monitoreado', valor_excel: '' },
        { id: 'UFIC-219', numero: 219, norma: 'R. 20.21.2.e', pregunta: 'No existen motores abiertos en puntos accesibles a personas o animales.', valor_excel: '' },
        { id: 'UFIC-220', numero: 220, norma: 'R. 20.21.2.h', pregunta: 'Los motores eléctricos que implican riesgos mecánicos para las personas cuentan con paradas de emergencia.', valor_excel: '' },
        { id: 'UFIC-221', numero: 221, norma: 'R. 20.21.2.i', pregunta: 'Todo motor con corriente nominal igual o superior a 3A, cuenta con una protección termo magnética dedicada.', valor_excel: '' },
        { id: 'UFIC-222', numero: 222, norma: 'R. 20.21.2. g', pregunta: 'El motor o generador es apropiado para el tipo de uso y condiciones ambientales del lugar donde opere.', valor_excel: '' },
        { id: 'UFIC-223', numero: 223, norma: 'N.110-16.f.1', pregunta: 'En paneles de distribucion y centros de control de motores cumple espacio dedicado, para la instalacion se debe disponesr de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta 7.6 m de altura o hasta el techo, en esta zona no se debe ubicar tuberia, ductos o equipos ajenoa, se permiten rociadores', valor_excel: '' },
        { id: 'UFIC-224', numero: 224, norma: 'R.20.21 .2 Parágrafo', pregunta: 'Para motores o generadores eléctricos de potencias mayores a 800 kW, el Certificado de Conformidad de Producto, podrá sustituirse por la declaración del proveedor donde se especifique que cumple el presente reglamento, indicar las normas técnicas aplicadas y los resultados de las pruebas tipo y de rutina realizadas por un laboratorio; esta auto certificación se hará dando estricto cumplimiento a los criterios de la norma internacional IEC 17050. Igual tratamiento se dará a motores o generadores reutilizados o re manufacturados de potencia superior a 200 kW.', valor_excel: '' },
        { id: 'UFIC-225', numero: 225, norma: 'R.20.24', pregunta: 'Las transferencias utilizadas en sistemas de emergencia, suplencias de circuitos, están incorporadas en un encerramiento según RETIE Núm.. 20.23.1.1', valor_excel: '' },
        { id: 'UFIC-226', numero: 226, norma: 'N.250-95', pregunta: 'El calibre del conductor de puesta a tierra de los equipos se puede calcular de acuerdo con la corriente nominal del dispositivo de protección del motor contra sobrecarga, pero no es menor al especificado en la Tabla 250-95', valor_excel: '' },
        { id: 'UFIC-227', numero: 227, norma: 'N.430-16', pregunta: 'En los lugares donde se acumulen polvo o sustancias voladoras se instalaron motores tipo cerrado para que no se sobrecalienten en condiciones normales de operación', valor_excel: '' },
      ],
    },
  ],
  observaciones: { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
};

export default RETIE_UFIYC_SCHEMA;