import { RETIEMasterSchema } from '../masterSchema';

export const RETIE_UF_RESIDENCIAL_SCHEMA: RETIEMasterSchema = {
  metadata: {
    code: 'UFR',
    name: 'Uso Final Residencial',
    version: '1.0.0',
    description: 'Lista de chequeo uso final residencial RETIE',
    category: 'residential',
    color: '#FFC000',
  },
  sheets: [
    {
      codigo: 'REQUISITOS_ACOMETIDA',
      titulo: '1. Requisitos generales de acometida',
      tipo: 'checklist',
      orden: 1,
      fields: [
        { id: 'UFR-001', label: 'El edificio u otra estructura a la que llegue la corriente eléctrica tiene solo una acometida.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-2.a' },
        { id: 'UFR-002', label: 'Si el edificio esta alimentado por más de un circuito o por una combinación de circuitos alimentadores y acometidas, en cada lugar de desconexión y cada ramal se instala una placa.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-2.b' },
        { id: 'UFR-003', label: 'Los conductores de acometida NO pasan a través del interior de otro edificio o estructura.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-3' },
        { id: 'UFR-004', label: 'Los conductores que no sean los de acometida no están instalados en la misma canalización de la acometida', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-7' },
        { id: 'UFR-005', label: 'En instalaciones monofásicas de capacidad instalable ≤ a 3 kVA el cable de acometida es de calibre no menor a 10 AWG', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 b.' },
        { id: 'UFR-006', label: 'En instalaciones de capacidad instalable entre 3 kVA y 10 kVA el cable de acometida es de calibre no menor a 8 AWG', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 b.' },
        { id: 'UFR-007', label: 'Si el cable de acometida es de aluminio, es de la serie AA8000 y la seccion es dos calibres mayor a la del conductor de cobre', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 b.' },
        { id: 'UFR-008', label: 'La regulación de tensión en la acometida no supera el 3%.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3.c.' },
        { id: 'UFR-009', label: 'En la fachada NO existen conductores a la vista, ni incrustados directamente. Los cables que lleguen a la caja del medidor estan encerrados en tubería metálica incrustada y en donde por limitaciones de los materiales de las paredes no se pueda hacer la incrustación, la canalización es certificada para intemperie y a prueba de impacto no menor al de la tubería tipo IMC.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 d.' },
        { id: 'UFR-010', label: 'Se aceptarán cables a la vista sólo si el cable de la acometida es tipo concéntrico con cubierta XLPE o HDPE, no presenta bucles que generen contaminación visual', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 d.' },
        { id: 'UFR-011', label: 'Los conductores de acometida NO presentan empalmes. Se aceptarian si se utilizan procedimiento técnico aprobado por el O.R.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-46\nR. 27.3 f.' },
      ],
    },
    {
      codigo: 'ACOMETIDA',
      titulo: '2. Acometida',
      tipo: 'checklist',
      orden: 2,
      fields: [
        { id: 'UFR-012', label: 'El tubo es galvanizado tipo intermedio o pesado y tiene capacete o elemento que impida el paso de agua.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3. a.' },
        { id: 'UFR-013', label: 'Se forma un bucle de goteo independiente en cada conductor. Se evita que la acometida se convierta en canal de transporte de agua lluvia a la fachada o al equipo de medida.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.27.3.e\nN.230-54.f' },
        { id: 'UFR-014', label: 'El tubo o poste permite el anclaje de una percha o gancho de sujeción de los cables de acometida', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3. a.' },
        { id: 'UFR-015', label: 'El tubo está fijado mecánicamente con templetes, o apoyos debidamente empotrados que no generen riesgos de volcamiento o rotura.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3. a.' },
        { id: 'UFR-016', label: 'La canalización que esta expuesta o a la vista tiene franjas de color naranja de al menos 10 cm de anchas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.6.a' },
        { id: 'UFR-017', label: 'Los cables de acometida AEREA están sujetos tanto a la estructura de soporte de la red de uso general como a la edificación a alimentar.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 a.' },
        { id: 'UFR-018', label: 'Los conductores de acometida soportan la exposición a los agentes atmosféricos y otras condiciones de uso sin que se produzcan fugas perjudiciales de corriente. Los conductores individuales esta aislados con un material termoplástico extruido o aislante termo ajustable.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-22' },
        { id: 'UFR-019', label: 'El cable de acometida aerea es del tipo antifraude como el concéntrico, o trenzado.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 b.' },
        { id: 'UFR-020', label: 'La altura de la acometida no es menor a 5,5 m (cruce de vías).', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3 a\nN 230-24.b.4' },
        { id: 'UFR-021', label: 'Los tramos aéreos de conductores a la vista y cables a la vista de varios conductores de no más de 600 V nominales, estan a una distancia vertical no menor a 2,5 m desde la superficie del tejado hacia arriba. La distancia vertical sobre el nivel del tejado se debe mantener para una distancia de no menos de 0,9 m desde el borde del tejado, en todas las direcciones.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-24 a.' },
        { id: 'UFR-022', label: 'Los conductores aéreos de acometida de no más de 600 V nominales, guardan la siguiente distancia mínima medida desde la superficie acabada del suelo: -1) 3,0 m en la acometida de la edificación, también en el punto más bajo del bucle de goteo de la entrada eléctrica al edificio y sobre las zonas o aceras accesibles sólo a los peatones y limitado a 150 V a tierra. -2) 3,6 m sobre edificios residenciales y accesos vehiculares y sobre las zonas comerciales no sujetas a tráfico de camiones, cuando la tensión esté limitada a 300 V a tierra. -3) 4,6 m en las zonas mencionadas en el punjo anterior .2), cuando la tensión supere los 300 V a tierra.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-24.b' },
        { id: 'UFR-023', label: '(cajas)-Sellado de las canalizaciones. Cuando una canalización de acometida entre desde la red de distribución SUBTERRANEA, esta sellada. También estan selladas las canalizaciones libres o no utilizadas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-8' },
        { id: 'UFR-024', label: 'Los conductores subterráneos de entrada de acometida son aislados para la tensión correspondiente.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-30' },
        { id: 'UFR-025', label: 'Se cumple la distancia mínima de enterramiento para acometida subterránea.(Tabla 300-5)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 300-5.a.' },
      ],
    },
    {
      codigo: 'ARMARIO_MEDIDORES',
      titulo: '3. Armario de medidores',
      tipo: 'checklist',
      orden: 3,
      fields: [
        { id: 'UFR-026', label: 'Se cumple con las distancias mínimas permitidas para el espacio de trabajo. Las puertas abren minimo 90°.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 10.4.\nN. 110-16' },
        { id: 'UFR-027', label: 'En paneles de distribucion y centros de control de motores ubicados en interiores se cumple espacio dedicado,en esta zona no se debe ubicar tuberia, ductos o equipos ajenos, se permiten rociadores. Para la instalacion se dispone de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta una altura de 7.6 m o hasta el techo,', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.384-4. a) 1)\nN.110-16 .f) 1)' },
        { id: 'UFR-028', label: 'El armario tiene logo de riesgo eléctrico, señalización de seguridad e identificación.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.4.f' },
        { id: 'UFR-029', label: 'El armario tiene adherida de manera clara, permanente y visible placa con características técnicas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.4. a-e' },
        { id: 'UFR-030', label: 'El armario tiene cuadro para identificar circuitos y diagrama unifilar actualizado.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.4.g,i' },
        { id: 'UFR-031', label: 'Los cables que lleguen a la caja del medidor están encerrados en tubería métallique incrustada', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.3.d' },
        { id: 'UFR-032', label: 'Existe un medio para desconectar todos los conductores a partir de los conductores de acometida (Protección principal).Es accionable desde fuera', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 230-74\nN. 230-78' },
        { id: 'UFR-033', label: 'La protección principal es automática y protege contra sobrecorriente.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.27.4.3.a,b' },
        { id: 'UFR-034', label: 'Un interruptor automático tiene especificaciones de corriente y tensión, no menores a los valores nominales de los circuitos que controla.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.2.2.b' },
        { id: 'UFR-035', label: 'En los interruptores automáticos el circuito alimentador llegue al terminal de línea y la salida se conecte a los terminales de carga.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.2.2. a' },
        { id: 'UFR-036', label: 'La capacidad de corriente del cable de acometida es superior a la capacidad de la protección asociada.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.27.4.3.c.' },
        { id: 'UFR-037', label: 'El equipo de acometida y todos los medios de desconexión esta rotulado para su uso.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-66 \nN.230-70.b' },
        { id: 'UFR-038', label: 'El alambrado, cableado (cable de acometida, barrajes, circuitos alimentadores) cumple el código de colores.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.3.f' },
        { id: 'UFR-039', label: 'Cableado-barrajes cumplen disposición de las fases; A, B, C, de frente a posterior; superior a inferior, o de izquierda a derecha, vista desde el frente del tablero.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.384-3. f)\nR. 20.23.1.2.d' },
        { id: 'UFR-040', label: 'Cuando la conexión involucra varias barras por fase, los conectores se coloca enfrentados y con espaciadores de cobre entre las barras', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.4.k' },
        { id: 'UFR-041', label: 'El armario cuenta con barrajes de tierra y neutro con suficientes terminales de salida.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.3.d' },
        { id: 'UFR-042', label: 'El equipo de acometida es adecuado para la corriente de corto circuito', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.230-65' },
        { id: 'UFR-043', label: 'Las aberturas no utilizadas están cerradas eficazmente', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.5.2.f' },
        { id: 'UFR-044', label: 'Los conductores con sección transversal 8 AWG y mayor instalados en canalizaciones son cableados.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.310-3' },
        { id: 'UFR-045', label: 'Para cable de aluminio, tiene conector bimetálico, se utiliza gel retardante a la oxidación.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.4.j' },
        { id: 'UFR-046', label: 'Los conductores instalados en el tablero, se conectan mediante terminal.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.3.a' },
        { id: 'UFR-047', label: 'No se instala dos o más conectores o terminales en la misma bornera o al mismo tornillo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.12.2.a' },
        { id: 'UFR-048', label: 'Los conductores de fase, neutro o el conductor puesto a tierra, de sección transversal menor a 1/0 AWG, "NO" están conectados en paralelo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.310-4' },
        { id: 'UFR-049', label: 'El conductor de puesta a tierra de equipos acompaña los conductores activos durante todo su recorrido y por la misma canalizacion', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.3.3. d' },
        { id: 'UFR-050', label: 'El conductor de tierra de cada circuito alimentador cumple el calibre mínimo dado en la tabla 250-95', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 250-95' },
        { id: 'UFR-051', label: 'La capacidad de corriente del conductor de fase es superior a la capacidad de la protección asociada para cada circuito. Ver tabla 310-16 NTC 2050', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.4.3.c' },
        { id: 'UFR-052', label: 'El conductor neutro y el de puesta a tierra son independientes entre sí y se conectan con un puente equipotencial, donde está la protección principal', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.4.' },
        { id: 'UFR-053', label: 'El puente de conexión equipotencial no es de menor calibre que el establecido en la Tabla 250-94 y sin empalmes', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-79.d\nN.250-53.b' },
        { id: 'UFR-054', label: 'No existen empalmes dentro del armario.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 373-8' },
        { id: 'UFR-055', label: 'Los cables NO atraviesan los barrajes', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.4.g' },
      ],
    },
    {
      codigo: 'SPT',
      titulo: '4. SPT',
      tipo: 'checklist',
      orden: 4,
      fields: [
        { id: 'UFR-056', label: 'La instalación eléctrica dispone de un sistema de puesta a tierra', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: '27.4.2.b' },
        { id: 'UFR-057', label: 'Existe caja de inspección SPT, es de mínimo 30 cm x 30 cm, o de 30 cm de diámetro si es circular y la tapa es removible.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.1.' },
        { id: 'UFR-058', label: 'Cada electrodo está enterrado en su totalidad y la parte superior del electrodo enterrado queda a mínimo 15 cm de la superficie.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.3.1.i' },
        { id: 'UFR-059', label: 'Toda conexión del SPT está limpia (de cemento, pinturas, lacas o barnices)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-118' },
        { id: 'UFR-060', label: 'No se usan como conductores de puesta a tierra conductores aislados o desnudos de Al o recubierto de cobre que estén en contacto directo con las paredes de mampostería o con tierra o si están sometidos a condiciones corrosivas. Cuando se utilicen en el exterior, no se instalaron a menos de 0,5 m del suelo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-92.a' },
        { id: 'UFR-061', label: 'El conductor de tierra de protección es de color verde o desnudo de Cu', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.6.3' },
        { id: 'UFR-062', label: 'El calibre del conductor del electrodo de puesta a tierra no es inferior al estipulado en la tabla 250-94 NTC 2050', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 250-94' },
        { id: 'UFR-063', label: 'Las conexiones que van bajo el nivel del suelo (SPT), se realizan con soldadura exotérmica o conector certificado para enterramiento directo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.1.' },
        { id: 'UFR-064', label: 'Al electrodo de puesta a tierra no se le conecta más de un conductor con la misma abrazadera o herraje, excepto si la abrazadera o herraje están certificados para usarlos con varios conductores.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-115' },
        { id: 'UFR-065', label: 'El electrodo tipo varilla o tubo tiene mínimo 2,4 m', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.3.1.f' },
        { id: 'UFR-066', label: 'No se permite el uso de aluminio en los electrodos de las puestas a tierra.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.3.1.b' },
        { id: 'UFR-067', label: 'Si existen varias puestas a tierra (Protección contra rayos, protección catódica, etc.), estan interconectadas eléctricamente', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.1.' },
        { id: 'UFR-068', label: 'Para la puesta a tierra de los sistemas eléctricos y equipos no se usa la puesta a tierra de pararrayos.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-86' },
        { id: 'UFR-069', label: 'No se usa como electrodo de puesta a tierra la instalación subterránea de tuberías metálicas de gas', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-83.a' },
        { id: 'UFR-070', label: 'Los apoyos o estructuras metálicas se encuentran puestas a tierra.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.' },
        { id: 'UFR-071', label: 'Se colocaron a tierra los armarios, cerramientos y canalizaciones metálicos de los conductores de la acometida y alimentadores', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-32  N.250-33' },
      ],
    },
    {
      codigo: 'TABLERO_DISTRIBUCION',
      titulo: '5. Tablero de distribución',
      tipo: 'checklist',
      orden: 5,
      fields: [
        { id: 'UFR-072', label: 'El Tablero de Distribucion es fácilmente accesible', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.27.4.3.d' },
        { id: 'UFR-073', label: 'Se cumple con las distancias mínimas permitidas para el espacio de trabajo. Las puertas abren minimo 90°.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 10.4.\nN. 110-16' },
        { id: 'UFR-074', label: 'El tablero tiene logo de riesgo eléctrico e identificación.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.4.f' },
        { id: 'UFR-075', label: 'En paneles de distribucion y centros de control de motores ubicados en interiores se cumple espacio dedicado,en esta zona no se debe ubicar tuberia, ductos o equipos ajenos, se permiten rociadores. Para la instalacion se dispone de espacios iguales al ancho y profundidad del equipo y extendiendose desde el piso hasta una altura de 7.6 m o hasta el techo,', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.384-4. a) 1)\nN.110-16 .f) 1)' },
        { id: 'UFR-076', label: 'El tablero tiene adherida de manera clara, permanente y visible placa con características técnicas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.4.a-e' },
        { id: 'UFR-077', label: 'El tablero tiene cuadro para identificar circuitos y diagrama unifilar actualizado.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.4.g,i' },
        { id: 'UFR-078', label: 'Las aberturas no utilizadas están cerradas eficazmente', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.5.2. f' },
        { id: 'UFR-079', label: 'NO existen empalmes dentro del tablero.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 373-8' },
        { id: 'UFR-080', label: 'Los cables no atraviesan barrajes', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.4.g' },
        { id: 'UFR-081', label: 'Se cumple el código de colores.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.3.f' },
        { id: 'UFR-082', label: 'Ningún circuito utiliza el blanco ni el verde para las fases.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.6.3' },
        { id: 'UFR-083', label: 'Cables o alambres de Aluminio o Alumino recubierto en cobre se cumple lo siguiente: 1. Son de la serie AA 8000.-2. Empleo de conectores bimetálicos - 3. Ser instalados y mantenidos por personas calificadas, con la competencia profesional certificada. -4. A toda conexión se le aplica gel retardantes de la oxidación. -5. Sobre el cuerpo del dispositivo o equipo para uso directo con conductores de aluminio, se fija rotulado de advertencia en fondo de color amarillo y letra negra.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.2.9.j' },
        { id: 'UFR-084', label: 'La capacidad de corriente del conductor de cada circuito ramal es superior a la capacidad de corriente de la protección asociada. Ver tabla 310-16 NTC 2050.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.4.3. c.' },
        { id: 'UFR-085', label: 'Cuando haya conductores en paralelo (sólo para mayores a calibres 1/0 AWG de Cu o Al) en varios conductos o cables, como lo permite el Artículo 310-4, el conductor de puesta a tierra de equipos, cuando exista está instalado en paralelo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 250-95' },
        { id: 'UFR-086', label: 'Cada circuito ramal presenta protección contra sobrecorriente.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.2.2.e' },
        { id: 'UFR-087', label: 'Cada circuito dispone de dispositivo de corte automático de la alimentación.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.27.4.1.e' },
        { id: 'UFR-088', label: 'En los interruptores automáticos el circuito alimentador llegue al terminal línea y la salida se conecte a los terminales carga.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.2.2.a' },
        { id: 'UFR-089', label: 'Los interruptores automáticos tienen unas especificaciones de corriente y tensión, no menores a los valores nominales de los circuitos que controlan.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.2.2.b' },
        { id: 'UFR-090', label: 'El tablero cuenta con barrajes de tierra y neutro, con suficientes terminales de salida.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.23.1.3. c.' },
        { id: 'UFR-091', label: 'No se instala dos o más conectores o terminales en la misma bornera o al mismo tornillo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.12.2.a' },
        { id: 'UFR-092', label: 'El tablero se encuentra sólidamente puesto a tierra.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.1.2.e' },
        { id: 'UFR-093', label: 'El conductor de puesta a tierra de equipos acompaña los conductores activos durante todo su recorrido y por la misma canalización.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 15.3.3.d.' },
        { id: 'UFR-094', label: 'El Conductor de puesta a tierra de equipos es continuo, sin interruptores o medios de desconexión y cuando se empalmen (es mecánica y eléctricamente seguro con soldadura o conector certificados para tal uso)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.15.3.3.c' },
        { id: 'UFR-095', label: 'El Conductor de puesta a tierra de equipos que por disposición de la instalación se requieran aislar, son de color verde, verde con rayas amarillas o identificados con marcas verdes en los puntos de inspección y extremos', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.15.3.3.e' },
        { id: 'UFR-096', label: 'El conductor de tierra de cada circuito ramal cumple el calibre mínimo dado en la tabla 250-95 NTC 2050.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 250-95' },
        { id: 'UFR-097', label: 'Para un Apto de área construida menor a 50 m² y capacidad instalable no mayor a 7 kVA, se tiene como mínimo los siguientes circuitos: - 1 circuito para pequeños artefactos de cocina, despensa y comedor de mínimo 20 A. - 1 circuito para plancha y lavado de mínimo 20 A. - 1 circuito para iluminación y tomacorrientes del resto de la vivienda de mínimo 20 A.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 28.1.g' },
        { id: 'UFR-098', label: 'Circuito de menos de 1000 V los conductores de conexión DPS a la red y a tierra no son de calibre menor a 14 AWG en Cu o 12 AWG en Al.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.280-21' },
        { id: 'UFR-099', label: 'Circuito de menos de 1000 V el valor nominal del descargador de sobretensiones es = o mayor que la máxima tensión continua de fase a tierra', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.280-4.a' },
        { id: 'UFR-100', label: 'En unidades de vivienda con capacidad instalable < o = a 7 kW, se permite que los tomacorrientes con interruptor de circuito por falla a tierra, puedan hacer parte del circuito para pequeños artefactos de cocina y de iluminación y fuerza en baños, siempre y cuando en el mesón de la cocina no se tengan más de dos salidas de tomacorriente doble y en el baño no más de una tomacorriente doble.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.28.1.a.' },
        { id: 'UFR-101', label: 'Realizar las pruebas de aislamiento: Las mediciones se realizan usando un megómetro a una tensión de por lo menos 500 Vcc. El valor de la resistencia de aislamiento no es menor de 1000 Ω/V.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.4.o' },
      ],
    },
    {
      codigo: 'CIRCUITOS_RAMALES',
      titulo: '6. Circuitos Ramales',
      tipo: 'checklist',
      orden: 6,
      fields: [
        { id: 'UFR-102', label: 'Existe toma GFCI instalada en los siguientes lugares: - Sobre el mesón de la cocina. - Adyacentes a lavamanos. - En garajes donde él tomacorriente se encuentre a nivel del suelo. - En exteriores con fácil acceso( menor de 1,9 m) - Sótanos sin terminado(Almacenamiento, trabajo o similar)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210.8' },
        { id: 'UFR-103', label: 'En los mostradores de las cocinas hay salidas de tomacorriente en cada espacio de pared de 0,3 m de ancho o más y de modo que ningún punto a lo largo de la línea de la pared quede a más de 0,6 m de un tomacorriente en ese espacio.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-52. c.1' },
        { id: 'UFR-104', label: 'Se instala por lo menos un tomacorriente en cada mostrador instalado de modo aislado en el centro de la cocina (islas), de 0,6 m o más x 0,3 m o más.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-52. c.2' },
        { id: 'UFR-105', label: 'Se instala por lo menos una salida de tomacorriente, en cada mostrador unido a la pared por un lado (penínsulas), de 0,6 m o más X 0,3 m o más.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-52. c.3' },
        { id: 'UFR-106', label: 'En los mostradores de las cocinas las salidas de tomacorriente "NO" están ubicadas a más de 0,5 m por encima del mostrador y "NO" se instalan salidas mirando hacia arriba en la superficie de los mostradores.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-52.c.5' },
        { id: 'UFR-107', label: 'Hay salidas de tomacorriente de modo que ningún punto a lo largo de la línea del suelo en ninguna pared este a más de 1.80 m de un tomacorriente en ese espacio.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210.52.a' },
        { id: 'UFR-108', label: 'En dormitorios con área ≤ a 9 m² se podrá aceptar que se disponga de sólo dos tomacorientes doubles, siempre que esten ubicados en paredes opuestas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.28.1.b' },
        { id: 'UFR-109', label: 'El tomacoriente instalado de forma horizontal, el contacto superior corresponde la neutro.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.10.2. f.' },
        { id: 'UFR-110', label: 'Un tomacoriente sencillo instalado en un circuito ramal individual tiene una capacidad de corriente no menor a la de dicho circuito.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-21. b.1' },
        { id: 'UFR-111', label: 'En las cajas para alojar equipos NO se retiraron las tapas de entrada de ductos no utilizadas, ni se hicieron perforaciones adicionales.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.5.2 e.' },
        { id: 'UFR-112', label: 'Las cajas están instaladas de modo que su borde frontal no se encuentra a más de 15 mm de la superficie de acabado final.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.5.2.c' },
        { id: 'UFR-113', label: 'En las salidas, uniones y de interruptores, queda como mínimo una longitud de 15 cm libre en los conductores.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.300-14' },
        { id: 'UFR-114', label: 'El empalme de diferentes conductores de puesta a tierra se hace dentro de la caja que los contiene y no en el aparato o equipo respectivamente.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-114' },
        { id: 'UFR-115', label: 'Todas las cajas metálicas que contengan aparatos están puestas a tierra por tornillo que no se dio ningún otro uso', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-114.a' },
        { id: 'UFR-116', label: 'Toda caja NO metálica que contenga aparatos se le instaló el respectivo conductor de puesta a tierra', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.250-114.b' },
        { id: 'UFR-117', label: 'Los conductores del sistema de puesta a tierra de equipos son continuos, sin interruptores y cuando se empalmen son mecánica y eléctricos seguros mediante soldadura o conectores certificados', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.15.3.3.c' },
        { id: 'UFR-118', label: 'Todas las carcasas o masas de equipos y cajas para alojar equipos (cajas de paso, tomacorientes, rosetas, canaletas, etc.) tienen conexión a tierra (MEDIDA EQUIPOTENCIAL)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 27.4.2.c.' },
        { id: 'UFR-119', label: 'Productos como: Las barras colectoras, terminales de cables, aisladores, interruptores, cajas para alojar equipos entre otros, no están dañados o contaminados por pintura, yeso, concreto, abrasivos o corrosivos', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.5.2.a\nR.20. k.' },
        { id: 'UFR-120', label: 'La conexión de los conductores eléctricos a los terminales de los tomacorientes y clavijas es lo suficientemente segura para evitar recalentamientos de los contactos.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.10.2.a' },
        { id: 'UFR-121', label: 'Los interruptores están provistos de sus respectivas tapas que impiden el contacto con partes energizadas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.16.3.2.e' },
        { id: 'UFR-122', label: 'NO se instalan tuberías no metálicas livianas (Tipo A), expuestas ni en cielos falsos.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.6.1.2. h.' },
        { id: 'UFR-123', label: 'En paredes o cielorrasos construidos en madera u otro material combustible, las cajas se instalaron a ras o sobresalen de la superficie de acabado', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.5.2.d' },
        { id: 'UFR-124', label: 'Existe tomacoriente con protección de falla a tierra en todos los espacios en condiciones de mayor vulnerabilidad como casos de piel mojada o sumergida (zona de lavado)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.28.1.c.' },
        { id: 'UFR-125', label: 'El tomacoriente para el equipo de lavandería, se instala a menos de 1,8 m del lugar destinado para el artefacto.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-50.c' },
        { id: 'UFR-126', label: 'Las canalizaciones expuestas o a la vista, están marcadas con franjas de color naranja de mínimo 10 cm', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.6.a.' },
        { id: 'UFR-127', label: 'El circuito de lavado NO tiene otras salidas asociadas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 220-4.c' },
        { id: 'UFR-128', label: 'Existe una tomacoriente monofásica de 125 V y 15 A o 20 A para el mantenimiento de los equipos de calefacción, congeladores y aire acondicionado en azoteas, aticos y espacios bajo el suelo', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-63' },
        { id: 'UFR-129', label: 'Existe mínimo una salida para alumbrado con interruptor de pared, en cada cuarto habitable', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-70. a' },
        { id: 'UFR-130', label: 'En escaleras interiores existe un interruptor de pared en cada planta ( 6 escalones o más)', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-70. a' },
        { id: 'UFR-131', label: 'En corredores y zonas similares de 3 m de largo o más, se instaló como mínimo un tomacoriente.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-52.h' },
      ],
    },
    {
      codigo: 'BANOS',
      titulo: '7. Baños',
      tipo: 'checklist',
      orden: 7,
      fields: [
        { id: 'UFR-132', label: 'En el cuarto del baño existe una salida para alumbrado con interruptor de pared.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 210-70. a' },
        { id: 'UFR-133', label: 'Las instalaciones localizadas en alturas por encima de 1500 msnm, tienen 1 circuito exclusivo para ducha eléctrica, a menos que se disponga de otro medio para el calentamiento del agua.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 28.1. g. 4.' },
        { id: 'UFR-134', label: 'La ducha eléctrica, esta instalada en circuito de capacidad no menor a 30 A para instalación monofásica a tensión menor de 150 V y 20 A para 208/220/240 V protegidos con un interruptor automático, con neutro y conductor de tierra plenamente identificados y conectado sólidamente a tierra o disponer de una protección diferencial.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 28.1. e.\nR.20.15.2. b' },
        { id: 'UFR-135', label: 'La ducha eléctrica se encuentra puesta a tierra', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.15.2 d.' },
        { id: 'UFR-136', label: 'En el cuarto de baño la ducha no tiene partes localizadas a menos de 2 m del piso.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.15.2. e.' },
        { id: 'UFR-137', label: 'En los cuartos de baño, se instaló por lo menos un tomacoriente en la pared adyacente a cada lavamanos y esta alimentado por circuito ramal de minimo 20 A.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.210-52.d' },
        { id: 'UFR-138', label: 'Las tomacorientes son GFCI y los interruptores noestan instalados a menos de 80 cm de la puerta de la zona de la ducha', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.28.1.d' },
      ],
    },
    {
      codigo: 'ILUMINACION',
      titulo: '8. Iluminación',
      tipo: 'checklist',
      orden: 8,
      fields: [
        { id: 'UFR-139', label: 'En los portalámparas la fase esta conectada en el terminal central y el neutro a la camisa roscada.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.29.2. a' },
        { id: 'UFR-140', label: 'Se asegura la evacuación de calor producida por la lámpara.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.29.2. b' },
        { id: 'UFR-141', label: 'Las cajas para salidas de alumbrado NO son rectangulares.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.5.2. b.' },
        { id: 'UFR-142', label: 'Se verifica funcionamiento de las luminarias de emergencia por un periodo minimo de 60 minutos despues de que se interrumpa el servicio electrico normal', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.17.1.c' },
      ],
    },
    {
      codigo: 'PRODUCTO',
      titulo: '9. Producto',
      tipo: 'checklist',
      orden: 9,
      fields: [
        { id: 'UFR-143', label: 'Todo producto esta rotulado con: la marca comercial, el nombre o logotipo del productor.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20. i.' },
        { id: 'UFR-144', label: 'En los conductores instalados, se cumple con el radio mínimo de curvatura que recomienda el productor.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.2.9.d.' },
        { id: 'UFR-145', label: 'No se instalan tuberías no metálicas en lugares expuestos a daños físicos o a la luz solar directa.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.6.1.2.f.' },
        { id: 'UFR-146', label: 'Las cintas aislantes usadas en instalaciones eléctricas exteriores son de color negro.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.9.2.' },
        { id: 'UFR-147', label: 'Los tomacorientes instalados en lugares sujetos a la lluvia o salpicadura de agua tienen cubierta protectora.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.10.2.c' },
        { id: 'UFR-148', label: 'En ambientes con chorros de agua (lugares de lavado) se emplearon enchufes y tomacorientes con encerramiento no menor a IP67 o su equivalente NEMA. Los tomacorientes GFCI no son aptas para estas aplicaciones, a menos que el productor así lo garantice.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.10.2.d' },
        { id: 'UFR-149', label: 'No se permite el cable sobre bandejas en instalaciones residenciales y demás excepciones definidas en la NTC', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.3.h' },
        { id: 'UFR-150', label: 'No hay tableros instalados en paredes contiguas a los peldaños de las escaleras.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.4. q' },
      ],
    },
    {
      codigo: 'CANALETA',
      titulo: '10. Canaleta',
      tipo: 'checklist',
      orden: 10,
      fields: [
        { id: 'UFR-151', label: 'No se permite el uso de canaletas no metálicas en: Instalaciones ocultas (excepto cuando atraviesan muros o paredes), donde estén expuestas a daño físico, en los espacios vacíos de ascensores, en ambientes con temperaturas superiores a las certificadas.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R. 20.6.2.2.a' },
        { id: 'UFR-152', label: 'Las canaletas están instaladas de tal manera que se asegura la continuidad mecánica y la continuidad eléctrica por medio de puentes equipotenciales.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.6.2.2. b' },
        { id: 'UFR-153', label: 'Estan sólidamente montadas y con encerramiento completo.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.6.2.2.c.' },
        { id: 'UFR-154', label: 'Se evita la abrasión o el corte del aislamiento de los conductores, mediante el uso de pasacables, tubos o accesorios adecuados.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.6.2.2. d.' },
      ],
    },
    {
      codigo: 'REQUISITOS_GENERALES',
      titulo: '11. Requisitos generales',
      tipo: 'checklist',
      orden: 11,
      fields: [
        { id: 'UFR-155', label: 'Los equipos eléctricos se instalaron de manera limpia y profesional.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.110-12' },
        { id: 'UFR-156', label: 'Los equipos eléctricos se instalaron firmemente a la superficie', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N. 110-13 .a' },
        { id: 'UFR-157', label: 'Los productos eléctricos fueron instalados para fines exclusivos para los que fueron certificados', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.110-3.b' },
        { id: 'UFR-158', label: 'Los conductores eléctricos (acometida, alimentador o circuitos ramales) se encuentran debidamente protegidos, cuando estén expuestos a daños físicos.', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'N.300-4' },
        { id: 'UFR-159', label: 'Se deben realizar las siguientes verificaciones: 1. Funcionalidad de las rejillas de ventilación, las tapas laterales y las puertas. 2. Identificaciones del tablero y de los conductores de control y potencia. 3. Conexión a tierra de las puertas. 4. Remover el polvo. 5. Medir equipotencialidad entre partes conductoras del tablero. 6. Verificar los torques de las uniones mecánicas, eléctricas y de anclaje. 7. Verificar los enclavamientos mecánicos de los equipos del tablero. 8. Inspeccionar visualmente de toda la estructura del tablero, especialmente la pintura. 9.Remover todos los objetos extraños (restos de cables, tuercas, tornillos, herramientas, etc.).', type: 'select', options: ['SI', 'NO', 'N/A'], required: true, norma: 'R.20.23.4.o' },
      ],
    },
  ],
};

export default RETIE_UF_RESIDENCIAL_SCHEMA;